package com.repss.apprepss;

import java.util.ArrayList;
import java.util.List;

/**
 * Created by maste on 14/03/2017.
 */

public class Constants {
    public static ArrayList<Causes> causes;
    public static ArrayList<String> intervenciones;

    public Constants(){

        causes = new ArrayList<>();
        intervenciones = new ArrayList<>();

    }
    
    public ArrayList<Causes> GetCauses(){

        Add("Vacunación Contra Tuberculosis (B.C.G.)","Intervenciones de salud pública");
        Add("Vacunación Contra Hepatitis B (H.B.)","Intervenciones de salud pública");
        Add("Administración De Vacuna Pentavalente (Dpt,  Hb, Hib)","Intervenciones de salud pública");
        Add("Vacunación Contra Rotavirus","Intervenciones de salud pública");
        Add("Vacunación Contra Neumococo Conjugado (Heptavalente)","Intervenciones de salud pública");
        Add("Vacunación Profiláctica Contra Influenza (Gripe Estacional) Menores De 14 Años Y Grupos De Riesgo","Intervenciones de salud pública");
        Add("Vacunación Contra Sarampión,  Parotiditis Y Rubéola (Srp)","Intervenciones de salud pública");
        Add("Vacunación Contra Difteria, Tosferina Y Tétanos (Dpt)","Intervenciones de salud pública");
        Add("Vacunación Contra Poliomielitis (Sabin)","Intervenciones de salud pública");
        Add("Vacunación Contra El Virus Del Papiloma Humano (Vph)","Intervenciones de salud pública");
        Add("Vacunación Contra Hepatitis B (Hb) Mayores De 14 Años","Intervenciones de salud pública");
        Add("Vacunación Contra Sarampión  Y Rubéola (Sr)","Intervenciones de salud pública");
        Add("Vacunación Contra Tétanos Y Difteria (Td)","Intervenciones de salud pública");
        Add("Vacunación Contra El Neumococo Para El Adulto  Mayor","Intervenciones de salud pública");
        Add("Vacunación Profiláctica Contra Influenza (Gripe Estacional) Para Mayores De 60 Años Sin Patologías Asociadas","Intervenciones de salud pública");
        Add("Acciones  Preventivas Para Recién Nacido","Intervenciones de salud pública");
        Add("Acciones  Preventivas Para Menores De 5 Años","Intervenciones de salud pública");
        Add("Acciones  Preventivas Para Niñas Y Niños  De 5 A 9 Años","Intervenciones de salud pública");
        Add("Detección Precoz De Los Trastornos De La Conducta Alimentaria","Intervenciones de salud pública");
        Add("Acciones  Preventivas Para Adolescentes De 10 A 19 Años","Intervenciones de salud pública");
        Add("Acciones  Preventivas Para Mujeres De 20 A 59 Años","Intervenciones de salud pública");
        Add("Acciones  Preventivas Para Hombres De 20 A 59 Años","Intervenciones de salud pública");
        Add("Examen Médico  Completo  Para Mujeres De 40 A 59 Años","Intervenciones de salud pública");
        Add("Examen Médico  Completo  Para Hombres De 40 A 59 Años","Intervenciones de salud pública");
        Add("Prevención Y Atención A Violencia Familiar Y De Género","Intervenciones de salud pública");
        Add("Acciones  Preventivas Para Adultos Mayores De 60 Años En Adelante","Intervenciones de salud pública");
        Add("Otras Acciones  De Promoción A La Salud Y Prevención  De Riesgos","Intervenciones de salud pública");
        Add("Diagnóstico Y Tratamiento De Anemia Ferropriva Y Por Deficiencia  De Vitamina B12","Intervenciones de atención de medicina general, familiar y especialidad");
        Add("Diagnóstico Y Tratamiento Por Deficiencia  De Vitamina A","Intervenciones de atención de medicina general, familiar y especialidad");
        Add("Diagnóstico Y Tratamiento De Escarlatina","Intervenciones de atención de medicina general, familiar y especialidad");
        Add("Diagnóstico Y Tratamiento De Sarampión,  Rubéola Y Parotiditis","Intervenciones de atención de medicina general, familiar y especialidad");
        Add("Diagnóstico Y Tratamiento De Varicela","Intervenciones de atención de medicina general, familiar y especialidad");
        Add("Diagnóstico Y Tratamiento De Faringoamigdalitis Aguda","Intervenciones de atención de medicina general, familiar y especialidad");
        Add("Diagnóstico Y Tratamiento De Tos Ferina","Intervenciones de atención de medicina general, familiar y especialidad");
        Add("Diagnóstico Y Tratamiento De Otitis Media No Supurativa","Intervenciones de atención de medicina general, familiar y especialidad");
        Add("Diagnóstico Y Tratamiento De Rinofaringitis Aguda","Intervenciones de atención de medicina general, familiar y especialidad");
        Add("Diagnóstico Y Tratamiento De Conjuntivitis","Intervenciones de atención de medicina general, familiar y especialidad");
        Add("Diagnóstico Y Tratamiento De Rinitis Alérgica Y Vasomotora","Intervenciones de atención de medicina general, familiar y especialidad");
        Add("Diagnóstico Y Tratamiento De Dengue Clásico (Y Otras Fiebres Producidas Por Flavivirus Y Arbovirus)","Intervenciones de atención de medicina general, familiar y especialidad");
        Add("Diagnóstico Y Tratamiento Del Síndrome  Diarreico  Agudo","Intervenciones de atención de medicina general, familiar y especialidad");
        Add("Diagnóstico Y Tratamiento De Fiebre Paratifoidea  Y Otras Salmonelosis","Intervenciones de atención de medicina general, familiar y especialidad");
        Add("Diagnóstico Y Tratamiento De Fiebre Tifoidea","Intervenciones de atención de medicina general, familiar y especialidad");
        Add("Diagnóstico Y Tratamiento Del Herpes Zóster","Intervenciones de atención de medicina general, familiar y especialidad");
        Add("Diagnóstico Y Tratamiento De Candidiasis Oral","Intervenciones de atención de medicina general, familiar y especialidad");
        Add("Diagnóstico Y Tratamiento De Gonorrea","Intervenciones de atención de medicina general, familiar y especialidad");
        Add("Diagnóstico Y Tratamiento De Infecciones Por Chlamydia  (Incluye Tracoma)","Intervenciones de atención de medicina general, familiar y especialidad");
        Add("Diagnóstico Y Tratamiento De Trichomoniasis","Intervenciones de atención de medicina general, familiar y especialidad");
        Add("Diagnóstico Y Tratamiento De Sífilis Precoz Y Tardía","Intervenciones de atención de medicina general, familiar y especialidad");
        Add("Diagnóstico Y Tratamiento De Cistitis","Intervenciones de atención de medicina general, familiar y especialidad");
        Add("Diagnóstico Y Tratamiento De Vaginitis  Aguda","Intervenciones de atención de medicina general, familiar y especialidad");
        Add("Diagnóstico Y Tratamiento De Vulvitis Aguda","Intervenciones de atención de medicina general, familiar y especialidad");
        Add("Diagnóstico Y Tratamiento De Chancro Blando","Intervenciones de atención de medicina general, familiar y especialidad");
        Add("Diagnóstico Y Tratamiento De Herpes Genital","Intervenciones de atención de medicina general, familiar y especialidad");
        Add("Diagnóstico Y Tratamiento De Amebiasis","Intervenciones de atención de medicina general, familiar y especialidad");
        Add("Diagnóstico Y Tratamiento De Anquilostomiasis Y Necatoriasis","Intervenciones de atención de medicina general, familiar y especialidad");
        Add("Diagnóstico Y Tratamiento De Ascariasis","Intervenciones de atención de medicina general, familiar y especialidad");
        Add("Diagnóstico Y Tratamiento De Enterobiasis","Intervenciones de atención de medicina general, familiar y especialidad");
        Add("Diagnóstico Y Tratamiento Farmacológico De Equinococosis","Intervenciones de atención de medicina general, familiar y especialidad");
        Add("Diagnóstico Y Tratamiento Farmacológico De Esquistosomiasis","Intervenciones de atención de medicina general, familiar y especialidad");
        Add("Diagnóstico Y Tratamiento Farmacológico De Estrongiloidiasis","Intervenciones de atención de medicina general, familiar y especialidad");
        Add("Diagnóstico Y Tratamiento Farmacológico De Filariasis","Intervenciones de atención de medicina general, familiar y especialidad");
        Add("Diagnóstico Y Tratamiento Farmacológico De Giardiasis","Intervenciones de atención de medicina general, familiar y especialidad");
        Add("Diagnóstico Y Tratamiento Farmacológico De Teniasis","Intervenciones de atención de medicina general, familiar y especialidad");
        Add("Diagnóstico Y Tratamiento Farmacológico De Tricuriasis","Intervenciones de atención de medicina general, familiar y especialidad");
        Add("Diagnóstico Y Tratamiento Farmacológico De Triquinosis","Intervenciones de atención de medicina general, familiar y especialidad");
        Add("Diagnóstico Y Tratamiento Farmacológico De Brucelosis","Intervenciones de atención de medicina general, familiar y especialidad");
        Add("Diagnóstico Y Tratamiento De Escabiosis","Intervenciones de atención de medicina general, familiar y especialidad");
        Add("Diagnóstico Y Tratamiento De Pediculosis Y Phthiriasis","Intervenciones de atención de medicina general, familiar y especialidad");
        Add("Diagnóstico Y Tratamiento De Micosis Superficiales (Excepto Onicomicosis)","Intervenciones de atención de medicina general, familiar y especialidad");
        Add("Diagnóstico Y Tratamiento De Onicomicosis","Intervenciones de atención de medicina general, familiar y especialidad");
        Add("Diagnóstico Y Tratamiento De Erisipela Y Celulitis","Intervenciones de atención de medicina general, familiar y especialidad");
        Add("Diagnóstico Y Tratamiento De Procesos Infecciosos De Rezago (Paludismo, Ricketsiosis, Lepra, Enfermedad De Chagas,  Leishmaniasis, Oncocercosis)","Intervenciones de atención de medicina general, familiar y especialidad");
        Add("Diagnóstico Y Tratamiento De Dermatitis Alérgica Y De Contacto","Intervenciones de atención de medicina general, familiar y especialidad");
        Add("Diagnóstico Y Tratamiento De Dermatitis Atópica","Intervenciones de atención de medicina general, familiar y especialidad");
        Add("Diagnóstico Y Tratamiento De Dermatitis De Contacto Por Irritantes","Intervenciones de atención de medicina general, familiar y especialidad");
        Add("Diagnóstico Y Tratamiento De Dermatitis Del Pañal","Intervenciones de atención de medicina general, familiar y especialidad");
        Add("Diagnóstico Y Tratamiento De Dermatitis Exfoliativa","Intervenciones de atención de medicina general, familiar y especialidad");
        Add("Diagnóstico Y Tratamiento De Dermatitis Seborreica","Intervenciones de atención de medicina general, familiar y especialidad");
        Add("Diagnóstico Y Tratamiento De Verrugas Vulgares","Intervenciones de atención de medicina general, familiar y especialidad");
        Add("Diagnóstico Y Tratamiento Del Acné","Intervenciones de atención de medicina general, familiar y especialidad");
        Add("Diagnóstico Y Tratamiento De Infección Aguda  Por Virus De La Hepatitis A Y B","Intervenciones de atención de medicina general, familiar y especialidad");
        Add("Diagnóstico Y Tratamiento De Gastritis Aguda,  Duodenitis Y Dispepsia","Intervenciones de atención de medicina general, familiar y especialidad");
        Add("Diagnóstico Y Tratamiento Del Síndrome  De Intestino Irritable","Intervenciones de atención de medicina general, familiar y especialidad");
        Add("Diagnóstico Y Tratamiento De Prediabetes Y Diabetes Mellitus Tipo 2","Intervenciones de atención de medicina general, familiar y especialidad");
        Add("Diagnóstico Y Tratamiento De Hipertensión Arterial","Intervenciones de atención de medicina general, familiar y especialidad");
        Add("Diagnóstico Y Tratamiento Conservador De Artrosis Erosiva Y Poliartrosis No Especificada","Intervenciones de atención de medicina general, familiar y especialidad");
        Add("Diagnóstico Y Tratamiento De Lumbalgia","Intervenciones de atención de medicina general, familiar y especialidad");
        Add("Atención Por Algunos  Signos,  Síntomas Y Otros Factores Que Influyen En El Estado De Salud","Intervenciones de atención de medicina general, familiar y especialidad");
        Add("Manejo  Ambulatorio  De Cuidados Paliativos Y Dolor Crónico","Intervenciones de atención de medicina general, familiar y especialidad");
        Add("Método De Planificación Familiar Temporal Con  Anticonceptivos Hormonales","Intervenciones de atención de medicina general, familiar y especialidad");
        Add("Consejo Y Asesoramiento  General Sobre Anticoncepción Mediante El Uso Del Condón","Intervenciones de atención de medicina general, familiar y especialidad");
        Add("Método De Planificación Familiar Temporal Con  Dispositivo  Intrauterino","Intervenciones de atención de medicina general, familiar y especialidad");
        Add("Atención Prenatal En El Embarazo","Intervenciones de atención de medicina general, familiar y especialidad");
        Add("Diagnóstico Y Tratamiento De Trastorno Por Déficit De Atención Con  Componente Hiperactivo","Intervenciones de atención de medicina general, familiar y especialidad");
        Add("Diagnóstico Y Tratamiento De Autismo  Y Síndrome  De Asperger","Intervenciones de atención de medicina general, familiar y especialidad");
        Add("Diagnóstico Y Tratamiento De Dismenorrea Primaria","Intervenciones de atención de medicina general, familiar y especialidad");
        Add("Diagnóstico Y Tratamiento Del Climaterio  Y Menopausia","Intervenciones de atención de medicina general, familiar y especialidad");
        Add("Diagnóstico Y Tratamiento De Trastornos Benignos De La Mama","Intervenciones de atención de medicina general, familiar y especialidad");
        Add("Diagnóstico Y Tratamiento De Hiperplasia Endometrial","Intervenciones de atención de medicina general, familiar y especialidad");
        Add("Diagnóstico Y Tratamiento De Vaginitis  Subaguda Y Crónica","Intervenciones de atención de medicina general, familiar y especialidad");
        Add("Diagnóstico Y Tratamiento De Endometriosis","Intervenciones de atención de medicina general, familiar y especialidad");
        Add("Diagnóstico Y Tratamiento De Uretritis Y Síndrome  Uretral","Intervenciones de atención de medicina general, familiar y especialidad");
        Add("Diagnóstico Y Tratamiento De Lesiones Escamosas Intraepiteliales De Grados Bajo Y Moderado","Intervenciones de atención de medicina general, familiar y especialidad");
        Add("Diagnóstico Y Tratamiento De Lesiones Escamosas Intraepiteliales De Alto Grado","Intervenciones de atención de medicina general, familiar y especialidad");
        Add("Diagnóstico Y Tratamiento De Desnutrición Leve, Moderada  Y Severa","Intervenciones de atención de medicina general, familiar y especialidad");
        Add("Diagnóstico Y Tratamiento De Desnutrición Severa Tipo Kwashiorkor","Intervenciones de atención de medicina general, familiar y especialidad");
        Add("Diagnóstico Y Tratamiento De Desnutrición Severa Tipo Marasmo","Intervenciones de atención de medicina general, familiar y especialidad");
        Add("Diagnóstico Y Tratamiento De Secuelas De Desnutrición","Intervenciones de atención de medicina general, familiar y especialidad");
        Add("Diagnóstico Y Tratamiento Médico  Del Sobrepeso Y Obesidad Exógena","Intervenciones de atención de medicina general, familiar y especialidad");
        Add("Diagnóstico Y Tratamiento De Laringotraqueítis Aguda","Intervenciones de atención de medicina general, familiar y especialidad");
        Add("Diagnóstico Y Tratamiento De Otitis Media Supurativa","Intervenciones de atención de medicina general, familiar y especialidad");
        Add("Diagnóstico Y Tratamiento De Sinusitis Aguda","Intervenciones de atención de medicina general, familiar y especialidad");
        Add("Diagnóstico Y Tratamiento Del Asma Y Sus Exacerbaciones En Adultos","Intervenciones de atención de medicina general, familiar y especialidad");
        Add("Diagnóstico Y Tratamiento Del Asma Y Sus Exacerbaciones En Menores De 18 Años","Intervenciones de atención de medicina general, familiar y especialidad");
        Add("Diagnóstico Y Tratamiento De Tuberculosis (Taes)","Intervenciones de atención de medicina general, familiar y especialidad");
        Add("Diagnóstico Y Tratamiento De Tuberculosis Farmacorresistente (Taes)","Intervenciones de atención de medicina general, familiar y especialidad");
        Add("Diagnóstico Y Tratamiento De Psoriasis","Intervenciones de atención de medicina general, familiar y especialidad");
        Add("Diagnóstico Y Tratamiento De Esofagitis Por Reflujo","Intervenciones de atención de medicina general, familiar y especialidad");
        Add("Diagnóstico Y Tratamiento De Úlcera Gástrica Y Péptica Crónica No Perforada","Intervenciones de atención de medicina general, familiar y especialidad");
        Add("Diagnóstico Y Tratamiento De Dislipidemia","Intervenciones de atención de medicina general, familiar y especialidad");
        Add("Diagnóstico Y Tratamiento De Hipertiroidismo","Intervenciones de atención de medicina general, familiar y especialidad");
        Add("Diagnóstico Y Tratamiento De Crisis Tirotóxica","Intervenciones de atención de medicina general, familiar y especialidad");
        Add("Diagnóstico Y Tratamiento De Hipotiroidismo","Intervenciones de atención de medicina general, familiar y especialidad");
        Add("Diagnóstico Y Tratamiento De Diabetes Mellitus Tipo 1","Intervenciones de atención de medicina general, familiar y especialidad");
        Add("Diagnóstico Y Tratamiento De Insuficiencia Cardiaca","Intervenciones de atención de medicina general, familiar y especialidad");
        Add("Diagnóstico Y Tratamiento De Osteoporosis","Intervenciones de atención de medicina general, familiar y especialidad");
        Add("Diagnóstico Y Tratamiento De Hiperuricemia Y Gota","Intervenciones de atención de medicina general, familiar y especialidad");
        Add("Diagnóstico Y Tratamiento De Artritis Reumatoide","Intervenciones de atención de medicina general, familiar y especialidad");
        Add("Diagnóstico Y Tratamiento De Trastornos Afectivos (Depresión,  Trastorno Afectivo De Tipo Bipolar, Trastornos Afectivos Persistentes)","Intervenciones de atención de medicina general, familiar y especialidad");
        Add("Diagnóstico Y Tratamiento De Trastornos De Ansiedad (Ansiedad  Generalizada, Trastornos De Pánico, Reacción A Estrés, Trastornos De Adaptación {Trastorno De Estrés Postraumático Y Trastorno Adaptativo})","Intervenciones de atención de medicina general, familiar y especialidad");
        Add("Diagnóstico Y Tratamiento De Trastornos Psicóticos (Esquizofrenia, Psicóticos Y Esquizotípico)","Intervenciones de atención de medicina general, familiar y especialidad");
        Add("Diagnóstico Y Tratamiento Ambulatorio  De Epilepsia Y Crisis Convulsivas","Intervenciones de atención de medicina general, familiar y especialidad");
        Add("Diagnóstico Y Tratamiento Médico  De Enfermedad De Parkinson","Intervenciones de atención de medicina general, familiar y especialidad");
        Add("Diagnóstico Y Tratamiento Conservador De Luxación Congénita De Cadera","Intervenciones de atención de medicina general, familiar y especialidad");
        Add("Rehabilitación De Fracturas","Intervenciones de atención de medicina general, familiar y especialidad");
        Add("Diagnóstico Y Tratamiento De Parálisis Facial","Intervenciones de atención de medicina general, familiar y especialidad");
        Add("Detección Temprana De Adicciones (Consejería)","Intervenciones de atención de medicina general, familiar y especialidad");
        Add("Prevención De Caries Dental","Intervenciones de odontología");
        Add("Aplicación De Selladores De Fosetas Y Fisuras Dentales","Intervenciones de odontología");
        Add("Restauraciones  Dentales Con  Amalgama, Ionómero De Vidrio Y Resina, Por Caries O Fractura De Los Dientes","Intervenciones de odontología");
        Add("Diagnóstico Y Tratamiento De Focos Infecciosos Bacterianos Agudos  En La Cavidad  Bucal","Intervenciones de odontología");
        Add("Extracción De Dientes Erupcionados Y Restos Radiculares","Intervenciones de odontología");
        Add("Terapia Pulpar","Intervenciones de odontología");
        Add("Extracción De Tercer Molar","Intervenciones de odontología");
        Add("Estabilización En Urgencias","Intervenciones en urgencias");
        Add("Estabilización En Urgencias  Por Crisis Hipertensiva","Intervenciones en urgencias");
        Add("Diagnóstico Y Tratamiento De La Cetoacidosis Diabética","Intervenciones en urgencias");
        Add("Diagnóstico Y Tratamiento Del Síndrome  Hiperglucémico Hiperosmolar  No Cetósico","Intervenciones en urgencias");
        Add("Diagnóstico Y Tratamiento De Angina De Pecho","Intervenciones en urgencias");
        Add("Atención En Urgencias  Por Intoxicación Aguda,  Uso Nocivo Y Estado De Abstinencia De Sustancias Adictivas","Intervenciones en urgencias");
        Add("Diagnóstico Y Tratamiento Del Envenenamiento Por Fenotiazinas","Intervenciones en urgencias");
        Add("Diagnóstico Y Tratamiento Del Envenenamiento Por Álcalis, Cáusticos Y Sustancias Alcalinas Similares","Intervenciones en urgencias");
        Add("Diagnóstico Y Tratamiento Del Envenenamiento Por Salicilatos","Intervenciones en urgencias");
        Add("Diagnóstico Y Tratamiento Del Envenenamiento Por Metanol","Intervenciones en urgencias");
        Add("Diagnóstico Y Tratamiento Del Envenenamiento Por Insecticidas Organofosforados Y Carbamatos","Intervenciones en urgencias");
        Add("Diagnóstico Y Tratamiento Del Envenenamiento Por Monóxido De Carbono","Intervenciones en urgencias");
        Add("Diagnóstico Y Tratamiento Del Envenenamiento Por Mordedura De Serpiente","Intervenciones en urgencias");
        Add("Diagnóstico Y Tratamiento De Picadura  De Alacrán","Intervenciones en urgencias");
        Add("Diagnóstico Y Tratamiento De Picaduras De Abeja, Araña Y Otros Artrópodos","Intervenciones en urgencias");
        Add("Diagnóstico Y Tratamiento De Intoxicación Aguda  Alimentaria","Intervenciones en urgencias");
        Add("Manejo  De Mordedura Y Prevención  De Rabia En Humanos","Intervenciones en urgencias");
        Add("Extracción De Cuerpos Extraños","Intervenciones en urgencias");
        Add("Curación Y Suturas De Lesiones Traumáticas  De Tejidos Blandos","Intervenciones en urgencias");
        Add("Diagnóstico Y Tratamiento Del Traumatismo Craneoencefálico Leve","Intervenciones en urgencias");
        Add("Manejo  En Urgencias  De Quemaduras  De Primer Grado","Intervenciones en urgencias");
        Add("Diagnóstico Y Tratamiento De Esguince Cervical","Intervenciones en urgencias");
        Add("Diagnóstico Y Tratamiento De Esguince De Hombro","Intervenciones en urgencias");
        Add("Diagnóstico Y Tratamiento De Esguince De Codo","Intervenciones en urgencias");
        Add("Diagnóstico Y Tratamiento De Esguince De Muñeca Y Mano","Intervenciones en urgencias");
        Add("Diagnóstico Y Tratamiento Conservador De Esguince De Rodilla","Intervenciones en urgencias");
        Add("Diagnóstico Y Tratamiento De Esguince De Tobillo Y Pie","Intervenciones en urgencias");
        Add("Diagnóstico Y Tratamiento De Pielonefritis","Intervenciones en hospitalización");
        Add("Diagnóstico Y Tratamiento De Bronquiolitis","Intervenciones en hospitalización");
        Add("Diagnóstico Y Tratamiento De Bronquitis Aguda","Intervenciones en hospitalización");
        Add("Diagnóstico Y Tratamiento De Meningitis Y Meningoencefalitis Agudas","Intervenciones en hospitalización");
        Add("Diagnóstico Y Tratamiento De Mastoiditis","Intervenciones en hospitalización");
        Add("Diagnóstico Y Tratamiento De Osteomielitis","Intervenciones en hospitalización");
        Add("Diagnóstico Y Tratamiento De Neumonía En Menores De 18 Años","Intervenciones en hospitalización");
        Add("Diagnóstico Y Tratamiento De Neumonía En Adultos","Intervenciones en hospitalización");
        Add("Diagnóstico Y Tratamiento De Absceso Hepático Amebiano","Intervenciones en hospitalización");
        Add("Diagnóstico Y Tratamiento De Enfermedad Pélvica Inflamatoria","Intervenciones en hospitalización");
        Add("Diagnóstico Y Tratamiento De Amenaza De Aborto","Intervenciones en hospitalización");
        Add("Diagnóstico Y Tratamiento De Amenaza De Parto Pretérmino","Intervenciones en hospitalización");
        Add("Atención Del Parto Y Puerperio Fisiológico","Intervenciones en hospitalización");
        Add("Diagnóstico Y Tratamiento De Pelviperitonitis","Intervenciones en hospitalización");
        Add("Diagnóstico Y Tratamiento De Endometritis Puerperal","Intervenciones en hospitalización");
        Add("Diagnóstico Y Tratamiento De Choque Séptico Puerperal","Intervenciones en hospitalización");
        Add("Atención Del Recién Nacido","Intervenciones en hospitalización");
        Add("Diagnóstico De Ictericia  Neonatal","Intervenciones en hospitalización");
        Add("Diagnóstico Y Tratamiento Del Recién Nacido Pretérmino  Sin Complicaciones","Intervenciones en hospitalización");
        Add("Diagnóstico Y Tratamiento Del Recién Nacido Pretérmino  Con  Hipotermia","Intervenciones en hospitalización");
        Add("Diagnóstico Y Tratamiento Del Pretérmino  Con  Bajo Peso Al Nacer","Intervenciones en hospitalización");
        Add("Diagnóstico Y Tratamiento De Preeclampsia Leve Y Moderada","Intervenciones en hospitalización");
        Add("Diagnóstico Y Tratamiento De Preeclampsia Severa","Intervenciones en hospitalización");
        Add("Diagnóstico Y Tratamiento De Eclampsia","Intervenciones en hospitalización");
        Add("Diagnóstico Y Tratamiento De Hemorragia Obstétrica Puerperal (Incluye Choque Hipovolémico)","Intervenciones en hospitalización");
        Add("Diagnóstico Y Tratamiento De Hemorragia Por Placenta Previa Y Desprendimiento Prematuro  De Placenta Normoinserta","Intervenciones en hospitalización");
        Add("Diagnóstico Y Tratamiento De Infección De Episiorrafia O Herida Quirúrgica Obstétrica","Intervenciones en hospitalización");
        Add("Diagnóstico Y Tratamiento De Litiasis Renal Y Ureteral","Intervenciones en hospitalización");
        Add("Diagnóstico Y Tratamiento De Litiasis De Vías Urinarias Inferiores","Intervenciones en hospitalización");
        Add("Diagnóstico Y Tratamiento Del Síndrome  Escrotal Agudo","Intervenciones en hospitalización");
        Add("Diagnóstico Y Tratamiento De Retención Aguda  De Orina","Intervenciones en hospitalización");
        Add("Diagnóstico Y Tratamiento De Prostatitis Aguda","Intervenciones en hospitalización");
        Add("Diagnóstico Y Tratamiento De Dengue Hemorrágico (Y Otras Complicaciones Por Flavivirus)","Intervenciones en hospitalización");
        Add("Diagnóstico Y Tratamiento De Traumatismo Craneoencefálico Moderado","Intervenciones en hospitalización");
        Add("Diagnóstico Y Tratamiento Conservador De Pancreatitis  Aguda","Intervenciones en hospitalización");
        Add("Diagnóstico Y Tratamiento Hospitalario Del Estatus Epiléptico Y Crisis Convulsivas De Difícil Control","Intervenciones en hospitalización");
        Add("Tratamiento Hospitalario De Hipertensión Arterial","Intervenciones en hospitalización");
        Add("Diagnóstico Y Tratamiento De Insuficiencia Cardiaca  Aguda  Y Del Edema Agudo Pulmonar","Intervenciones en hospitalización");
        Add("Diagnóstico Y Tratamiento De Enfermedad Pulmonar  Obstructiva  Crónica","Intervenciones en hospitalización");
        Add("Diagnóstico Y Tratamiento De Neuropatía Periférica Secundaria  A Diabetes","Intervenciones en hospitalización");
        Add("Tratamiento Hospitalario De Úlcera Y Del Pie Diabético Infectados","Intervenciones en hospitalización");
        Add("Diagnóstico Y Tratamiento Hospitalario De Quemaduras  De Segundo Grado","Intervenciones en hospitalización");
        Add("Diagnóstico Y Tratamiento De Hemorragia Digestiva","Intervenciones en hospitalización");
        Add("Diagnóstico Y Tratamiento Del Síndrome  De Hellp","Intervenciones en hospitalización");
        Add("Diagnóstico Y Tratamiento De Corioamnioítis","Intervenciones en hospitalización");
        Add("Diagnóstico Y Tratamiento De Embolia Obstétrica","Intervenciones en hospitalización");
        Add("Diagnóstico Y Tratamiento De Diabetes Gestacional","Intervenciones en hospitalización");
        Add("Diagnóstico Y Tratamiento De Hipertensión Inducida Y/O Preexistente En El Embarazo","Intervenciones en hospitalización");
        Add("Diagnóstico Y Tratamiento De Trombosis Venosa Profunda En El Embarazo Y Puerperio","Intervenciones en hospitalización");
        Add("Laparotomía Exploradora","Intervenciones de cirugía general");
        Add("Diagnóstico Y Tratamiento De Apendicitis","Intervenciones de cirugía general");
        Add("Esplenectomía","Intervenciones de cirugía general");
        Add("Diagnóstico Y Tratamiento De Enfermedad Diverticular","Intervenciones de cirugía general");
        Add("Diagnóstico Y Tratamiento Quirúrgico De Isquemia E Infarto  Intestinal","Intervenciones de cirugía general");
        Add("Diagnóstico Y Tratamiento De Obstrucción Intestinal E Ileo","Intervenciones de cirugía general");
        Add("Diagnóstico Y Tratamiento Quirúrgico De Perforación Gástrica Y/O Intestinal","Intervenciones de cirugía general");
        Add("Diagnóstico Y Tratamiento Del Vólvulo","Intervenciones de cirugía general");
        Add("Diagnóstico Y Tratamiento Del Absceso Perirrectal","Intervenciones de cirugía general");
        Add("Diagnóstico Y Tratamiento De Fístula Y/O La Fisura Anal","Intervenciones de cirugía general");
        Add("Diagnóstico Y Tratamiento De Enfermedad Hemorroidal","Intervenciones de cirugía general");
        Add("Diagnóstico Y Tratamiento De Hernia Hiatal","Intervenciones de cirugía general");
        Add("Diagnóstico Y Tratamiento De Hipertrofia Congénita Del Píloro","Intervenciones de cirugía general");
        Add("Diagnóstico Y Tratamiento De Hernia Crural","Intervenciones de cirugía general");
        Add("Diagnóstico Y Tratamiento De Hernia Inguinal","Intervenciones de cirugía general");
        Add("Diagnóstico Y Tratamiento De Hernia Umbilical","Intervenciones de cirugía general");
        Add("Diagnóstico Y Tratamiento De Hernia Ventral","Intervenciones de cirugía general");
        Add("Diagnóstico Y Tratamiento De Colecistitis  Y Colelitiasis","Intervenciones de cirugía general");
        Add("Diagnóstico Y Tratamiento Quirúrgico De Los Condilomas","Intervenciones de cirugía general");
        Add("Diagnóstico Y Tratamiento De Quistes De Ovario","Intervenciones de cirugía general");
        Add("Diagnóstico Y Tratamiento De Torsión De Anexos","Intervenciones de cirugía general");
        Add("Método Definitivo De Planificación Familiar En La Mujer (Oclusión Tubaria Bilateral)","Intervenciones de cirugía general");
        Add("Diagnóstico Y Tratamiento Quirúrgico De Enfermedad Trofoblástica","Intervenciones de cirugía general");
        Add("Diagnóstico Y Tratamiento Quirúrgico Del Embarazo Ectópico","Intervenciones de cirugía general");
        Add("Diagnóstico Y Tratamiento Del Aborto Incompleto (No  Incluye Interrupción Legal Del Embarazo)","Intervenciones de cirugía general");
        Add("Atención De Cesárea Y Puerperio Quirúrgico","Intervenciones de cirugía general");
        Add("Reparación  Uterina","Intervenciones de cirugía general");
        Add("Ablación Endometrial","Intervenciones de cirugía general");
        Add("Tratamiento Laparoscópico De La Endometriosis","Intervenciones de cirugía general");
        Add("Diagnóstico Y Tratamiento De Miomatosis  Uterina","Intervenciones de cirugía general");
        Add("Histerectomía Abdominal Y Vaginal","Intervenciones de cirugía general");
        Add("Diagnóstico Y Tratamiento Del Prolapso Genital Femenino (Colpoperineoplastía)","Intervenciones de cirugía general");
        Add("Método Definitivo De Planificación Familiar En Hombres (Vasectomía)","Intervenciones de cirugía general");
        Add("Circuncisión","Intervenciones de cirugía general");
        Add("Orquidopexia","Intervenciones de cirugía general");
        Add("Diagnóstico Y Tratamiento De Hiperplasia De La Próstata","Intervenciones de cirugía general");
        Add("Extirpación De Lesión Cancerosa  De Piel (No  Incluye Melanoma)","Intervenciones de cirugía general");
        Add("Extirpación De Tumor  Benigno  En Tejidos Blandos","Intervenciones de cirugía general");
        Add("Amigdalectomía Con  O Sin Adenoidectomía","Intervenciones de cirugía general");
        Add("Tratamiento Quirúrgico De Papiloma Faríngeo  (Incluye Papiloma Laríngeo)","Intervenciones de cirugía general");
        Add("Reparación  De Labio Hendido Con  O Sin Paladar Hendido","Intervenciones de cirugía general");
        Add("Cirugía  De Acortamiento Muscular Para Estrabismo","Intervenciones de cirugía general");
        Add("Cirugía  De Alargamiento Muscular Para Estrabismo","Intervenciones de cirugía general");
        Add("Tratamiento Quirúrgico De Glaucoma","Intervenciones de cirugía general");
        Add("Tratamiento Quirúrgico De Pterigión","Intervenciones de cirugía general");
        Add("Tratamiento Quirúrgico De Hidrocefalia","Intervenciones de cirugía general");
        Add("Colocación Y Retiro De Diversos Catéteres","Intervenciones de cirugía general");
        Add("Disección Radical De Cuello","Intervenciones de cirugía general");
        Add("Toracotomía, Pleurotomía  Y Drenaje De Tórax","Intervenciones de cirugía general");
        Add("Tratamiento Quirúrgico De Luxación Congénita De Cadera","Intervenciones de cirugía general");
        Add("Tratamiento Quirúrgico De Pie Equino En Niños","Intervenciones de cirugía general");
        Add("Safenectomía","Intervenciones de cirugía general");
        Add("Reducción De Luxaciones Bajo Anestesia Por Manipulación","Intervenciones de cirugía general");
        Add("Reducción Quirúrgica De Fractura De Clavícula","Intervenciones de cirugía general");
        Add("Reducción Quirúrgica De Fractura De Húmero","Intervenciones de cirugía general");
        Add("Reducción Quirúrgica De Fractura De Cúbito Y Radio","Intervenciones de cirugía general");
        Add("Reducción Quirúrgica De Fractura De Mano","Intervenciones de cirugía general");
        Add("Reducción Quirúrgica De Fractura De Cadera","Intervenciones de cirugía general");
        Add("Reducción Quirúrgica De Fractura De Fémur","Intervenciones de cirugía general");
        Add("Reducción Quirúrgica De Fractura De Tibia Y Peroné","Intervenciones de cirugía general");
        Add("Reducción Quirúrgica De Fractura De Tobillo Y Pie","Intervenciones de cirugía general");
        Add("Tratamiento Artroscópico De Las Lesiones De La Rodilla","Intervenciones de cirugía general");
        Add("Artroplastía Total De Rodilla","Intervenciones de cirugía general");
        Add("Amputación De Miembro Inferior Secundaria  A Pie Diabético","Intervenciones de cirugía general");
        Add("Tratamiento De Quiste Sinovial Y Ganglión","Intervenciones de cirugía general");
        Add("Diagnóstico Y Tratamiento De Arritmias Cardiacas","Intervenciones de cirugía general");
        Add("Diagnóstico Y Tratamiento Quirúrgico De Cataratas","Intervenciones de cirugía general");

        return causes;
    }

    public ArrayList<Causes> GetGastosCatastroficos(){
        Add("Peso Extremadamente Bajo Al Nacer","UCIN");
        Add("Síndrome  De Dificultad  Respiratoria Del Recién Nacido","UCIN");
        Add("Sepsis Del Recién Nacido Debida A Estreptococo Del Grupo B","UCIN");
        Add("Atresia Anal","Malformaciones congénitas, quirúrgicas  y adquiridas");
        Add("Atresia Esofágica","Malformaciones congénitas, quirúrgicas  y adquiridas");
        Add("Atresia Intestinal","Malformaciones congénitas, quirúrgicas  y adquiridas");
        Add("Onfalocele","Malformaciones congénitas, quirúrgicas  y adquiridas");
        Add("Gastrosquisis","Malformaciones congénitas, quirúrgicas  y adquiridas");
        Add("Atresia-Estenosis Duodenal","Malformaciones congénitas, quirúrgicas  y adquiridas");
        Add("Espina Bífida","Malformaciones congénitas, quirúrgicas  y adquiridas");
        Add("Estenosis Ureteral","Malformaciones congénitas, quirúrgicas  y adquiridas");
        Add("Estenosis Del Meato Uretral","Malformaciones congénitas, quirúrgicas  y adquiridas");
        Add("Estenosis Ureteral","Malformaciones congénitas, quirúrgicas  y adquiridas");
        Add("Extrofia Vesical","Malformaciones congénitas, quirúrgicas  y adquiridas");
        Add("Hipoplasia/Displasia Renal","Malformaciones congénitas, quirúrgicas  y adquiridas");
        Add("Hipospadias-Epispadias","Malformaciones congénitas, quirúrgicas  y adquiridas");
        Add("Uréter  Retrocavo","Malformaciones congénitas, quirúrgicas  y adquiridas");
        Add("Ureterocele","Malformaciones congénitas, quirúrgicas  y adquiridas");
        Add("Estenosis Uretral","Malformaciones congénitas, quirúrgicas  y adquiridas");
        Add("Uréter  Éctópico (Meatos  Ectópicos)","Malformaciones congénitas, quirúrgicas  y adquiridas");
        Add("Malformaciones Congénitas Cardiacas","Malformaciones congénitas, quirúrgicas  y adquiridas");
        Add("Deficiencia  Del Factor Viii","Enfermedades metabólicas");
        Add("Deficiencia  Del Factor Ix","Enfermedades metabólicas");
        Add("Enfermedad De Von Willebrand","Enfermedades metabólicas");
        Add("Enfermedad De Fabry / Enfermedad De Gaucher","Enfermedades metabólicas");
        Add("Mucopolisacaridosis Tipo I","Enfermedades metabólicas");
        Add("Mucopolisacaridosis Tipo Ii","Enfermedades metabólicas");
        Add("Mucopolisacaridosis Tipo Vi","Enfermedades metabólicas");
        Add("Enfermedad De Pompe","Enfermedades metabólicas");
        Add("Astrocitoma","Enfermedades metabólicas");
        Add("Ependimoma","Cáncer  en menores de 18 años");
        Add("Meduloblastoma","Cáncer  en menores de 18 años");
        Add("Neuroblastoma","Cáncer  en menores de 18 años");
        Add("Otros Tumores Del Snc*","Cáncer  en menores de 18 años");
        Add("Tumor  De Wilms","Cáncer  en menores de 18 años");
        Add("Otros Tumores Renales*","Cáncer  en menores de 18 años");
        Add("Leucemia Linfoblástica  Aguda","Cáncer  en menores de 18 años");
        Add("Leucemia Mieloblástica  Aguda","Cáncer  en menores de 18 años");
        Add("Leucemias Crónicas","Cáncer  en menores de 18 años");
        Add("Síndromes  Mielodisplásicos","Cáncer  en menores de 18 años");
        Add("Hepatocarcinoma","Cáncer  en menores de 18 años");
        Add("Hepatoblastoma","Cáncer  en menores de 18 años");
        Add("Osteosarcoma","Cáncer  en menores de 18 años");
        Add("Sarcoma De Ewing","Cáncer  en menores de 18 años");
        Add("Linfoma No Hodgkin","Cáncer  en menores de 18 años");
        Add("Enfermedad O Linfoma De Hodgkin","Cáncer  en menores de 18 años");
        Add("Retinoblastoma","Cáncer  en menores de 18 años");
        Add("Sarcoma De Partes Blandas","Cáncer  en menores de 18 años");
        Add("Tumores Gonadales Y Extragonadales","Cáncer  en menores de 18 años");
        Add("Tumores Extragonadales","Cáncer  en menores de 18 años");
        Add("Diversos Carcinomas*","Cáncer  en menores de 18 años");
        Add("Histiocitosis Maligna","Cáncer  en menores de 18 años");
        Add("Tumor  Maligno De Ovario","Cáncer  en mayores de 18 años");
        Add("Tumor  Maligno De Próstata","Cáncer  en mayores de 18 años");
        Add("Seminoma Y No Seminoma","Cáncer  en mayores de 18 años");
        Add("Cáncer  Cervicouterino","Cáncer  en mayores de 18 años");
        Add("Cáncer  De Mama","Cáncer  en mayores de 18 años");
        Add("Tumor  Maligno De Colon","Cáncer  en mayores de 18 años");
        Add("Tumor  Maligno De La Unión  Recto Sigmoidea","Cáncer  en mayores de 18 años");
        Add("Tumor  Maligno De Recto","Cáncer  en mayores de 18 años");
        Add("Folicular","Cáncer  en mayores de 18 años");
        Add("Difuso","Cáncer  en mayores de 18 años");
        Add("Infarto  Agudo Al Miocardio","Menores  de 60 años");
        Add("Hepatitis Viral Tipo C Crónica","20 a 50 años");
        Add("Trasplante De Cornea","Paciente  pediátrico y adulto");
        Add("Trasplante De Medula  Ósea Menores De 18 Años","Paciente  pediátrico y adulto");
        Add("Trasplante Renal Menores De 18 Años","Paciente  pediátrico y adulto");
        Add("Síndrome  De Turner","Paciente  pediátrico y adulto");

        return causes;
    }

    public ArrayList<Causes> GetSeguroMedico(){

        Add("Tuberculosis Del Sistema Nervioso","Ciertas  enfermedades infecciosas y parasitarias");
        Add("Tuberculosis Miliar","Ciertas  enfermedades infecciosas y parasitarias");
        Add("Listeriosis","Ciertas  enfermedades infecciosas y parasitarias");
        Add("Tétanos  Neonatal","Ciertas  enfermedades infecciosas y parasitarias");
        Add("Septicemia  No Especificada (Incluye  Choque Séptico)","Ciertas  enfermedades infecciosas y parasitarias");
        Add("Sífilis Congénita","Ciertas  enfermedades infecciosas y parasitarias");
        Add("Encefalitis Viral, No Especificada","Ciertas  enfermedades infecciosas y parasitarias");
        Add("Enfermedad Debida A Virus Citomegálico","Ciertas  enfermedades infecciosas y parasitarias");
        Add("Toxoplasmosis","Ciertas  enfermedades infecciosas y parasitarias");
        Add("Tumor  Benigno  De Las Glándulas Salivales Mayores (Ránula)","Tumores");
        Add("Tumor  Benigno  Del Mediastino","Tumores");
        Add("Tumor  Benigno  De La Piel Del Labio","Tumores");
        Add("Tumor  Benigno  Del Ojo Y Sus Anexos","Tumores");
        Add("Púrpura  Trombocitopénica Idiopática","Enfermedades de la sangre y de los órganos hematopoyéticos y ciertos trastornos que afectan  el mecanismo de la inmunidad");
        Add("Inmunodeficiencia Con Predominio De Defectos De Los Anticuerpos","Enfermedades de la sangre y de los órganos hematopoyéticos y ciertos trastornos que afectan  el mecanismo de la inmunidad");
        Add("Inmunodeficiencias Combinadas","Enfermedades de la sangre y de los órganos hematopoyéticos y ciertos trastornos que afectan  el mecanismo de la inmunidad");
        Add("Otras Inmunodeficiencias","Enfermedades de la sangre y de los órganos hematopoyéticos y ciertos trastornos que afectan  el mecanismo de la inmunidad");
        Add("Intolerancia A La Lactosa","Enfermedades endocrinas, nutricionales y metabólicas");
        Add("Fibrosis Quística","Enfermedades endocrinas, nutricionales y metabólicas");
        Add("Depleción Del Volumen","Enfermedades endocrinas, nutricionales y metabólicas");
        Add("Hiperplasia Congénita De Glándulas  Suprarrenales,","Enfermedades endocrinas, nutricionales y metabólicas");
        Add("Fenilcetonuria","Enfermedades endocrinas, nutricionales y metabólicas");
        Add("Galactosemia","Enfermedades endocrinas, nutricionales y metabólicas");
        Add("Otros Trastornos Del Nervio Facial","Enfermedades del sistema nervioso");
        Add("Síndrome  De Guillain-Barré","Enfermedades del sistema nervioso");
        Add("Parálisis Cerebral  Infantil (Diagnóstico, Terapia  Y En Su Caso, Los Insumos  O Medicamentos Especializados  Utilizados;  Anual Y Hasta Por 5 Años).","Enfermedades del sistema nervioso");
        Add("Hemiplejía (Diagnóstico, Terapia  Y En Su Caso, Los Insumos  O Medicamentos Especializados Utilizados;  Anual Y Hasta Por 5 Años).","Enfermedades del sistema nervioso");
        Add("Paraplejía Y Cuadriplejía (Diagnóstico, Terapia  Y En Su Caso, Los Insumos  O Medicamentos Especializados  Utilizados;  Anual Y Hasta Por 5 Años).","Enfermedades del sistema nervioso");
        Add("Retinopatía De La Prematuridad","Enfermedades del ojo");
        Add("Hipoacusia Neurosensorial Bilateral (Prótesis  Auditiva Externa Y Sesiones De Rehabilitación Auditiva Verbal)","Enfermedades del oído");
        Add("Habilitación Auditiva Verbal En Niños No Candidatos A Implantación De Prótesis De Cóclea (Anual  Hasta Por 5 Años)","Enfermedades del oído");
        Add("Implantación Prótesis Cóclea","Enfermedades del oído");
        Add("Habilitación Auditiva Verbal (Anual  Hasta Por 5 Años).","Enfermedades del oído");
        Add("Miocarditis  Aguda","Enfermedades del sistema circulatorio");
        Add("Fibroelastosis  Endocárdica","Enfermedades del sistema circulatorio");
        Add("Hipertensión Pulmonar Primaria","Enfermedades del sistema circulatorio");
        Add("Neumonía Por Influenza Por Virus Identificado","Enfermedades del sistema respiratorio");
        Add("Neumonía Por Influenza Por Virus No Identificado","Enfermedades del sistema respiratorio");
        Add("Neumonía Bacteriana No Clasificada En Otra Parte","Enfermedades del sistema respiratorio");
        Add("Bronconeumonía, No Especificada","Enfermedades del sistema respiratorio");
        Add("Neumonitis Debida A Sólidos Y Líquidos","Enfermedades del sistema respiratorio");
        Add("Piotórax","Enfermedades del sistema respiratorio");
        Add("Derrame Pleural No Clasificado En Otra Parte","Enfermedades del sistema respiratorio");
        Add("Derrame Pleural En Afecciones Clasificadas En Otra Parte","Enfermedades del sistema respiratorio");
        Add("Neumotórax","Enfermedades del sistema respiratorio");
        Add("Otros Trastornos Respiratorios (Incluye  Enfermedades De La Tráquea  Y De Los Bronquios, No Clasificadas En Otra Parte,  Colapso Pulmonar, Enfisema Intersticial, Enfisema Compensatorio, Otros Trastornos Del Pulmón, Enfermedades Del Mediastino, No Clasificadas En Otra Parte, Trastornos Del Diafragma, Otros Trastornos Respiratorios Especificados)","Enfermedades del sistema respiratorio");
        Add("Trastornos Del Desarrollo  Y De La Erupción  De Los Dientes","Enfermedades del sistema digestivo");
        Add("Estomatitis Y Lesiones Afines","Enfermedades del sistema digestivo");
        Add("Otras Enfermedades Del Esófago (Incluye  Acalasia Del Cardias, Úlcera Del Esófago, Obstrucción Del Esófago, Perforación Del Esófago, Disquinesia Del Esófago, Divertículo Del Esófago, Adquirido, Síndrome  De Laceración Y Hemorragia Gastroesofágicas, Otras Enfermedades Especificadas Del Esófago, Enfermedad Del Esófago, No Especificada)","Enfermedades del sistema digestivo");
        Add("Constipación","Enfermedades del sistema digestivo");
        Add("Malabsorción Intestinal","Enfermedades del sistema digestivo");
        Add("Otros Trastornos Del Sistema Digestivo Consecutivos  A Procedimientos, No Clasificados En Otra Parte","Enfermedades del sistema digestivo");
        Add("Síndrome  Estafilocócico De La Piel Escaldada (Síndrome De Ritter)","Enfermedades de la piel");
        Add("Absceso Cutáneo, Furúnculo Y Carbunco","Enfermedades de la piel");
        Add("Quiste  Epidérmico","Enfermedades del sistema osteomuscular");
        Add("Artritis  Piógena","Enfermedades del sistema osteomuscular");
        Add("Artritis  Juvenil","Enfermedades del sistema osteomuscular");
        Add("Poliarteritis Nodosa Y Afecciones Relacionadas","Poliarteritis nodosa y afecciones relacionadas");
        Add("Fascitis Necrotizante","Enfermedades del sistema genitourinario");
        Add("Síndrome  Nefrítico  Agudo","Enfermedades del sistema genitourinario");
        Add("Síndrome  Nefrótico, Anomalía Glomerular Mínima","Enfermedades del sistema genitourinario");
        Add("Uropatía  Obstructiva Y Por Reflujo","Enfermedades del sistema genitourinario");
        Add("Insuficiencia Renal Aguda","Enfermedades del sistema genitourinario");
        Add("Insuficiencia Renal Terminal","Enfermedades del sistema genitourinario");
        Add("Divertículo De La Vejiga","Enfermedades del sistema genitourinario");
        Add("Infección  De Vías Urinarias, Sitio No Especificado","Enfermedades del sistema genitourinario");
        Add("Hidrocele Y Espermatocele","Enfermedades del sistema genitourinario");
        Add("Orquitis Y Epididimitis","Enfermedades del sistema genitourinario");
        Add("Fístula Vesicovaginal","Ciertas  afecciones originadas  en el periodo perinatal");
        Add("Feto Y Recién Nacido Afectados Por Trastornos Hipertensivos De La Madre","Ciertas  afecciones originadas  en el periodo perinatal");
        Add("Feto Y Recién Nacido Afectados Por Ruptura Prematura De Membranas","Ciertas  afecciones originadas  en el periodo perinatal");
        Add("Feto Y Recién Nacido Afectado Por Complicaciones De La Placenta, Del Cordón Umbilical  Y De Las Membranas","Ciertas  afecciones originadas  en el periodo perinatal");
        Add("Feto Y Recién Nacido Afectados Por Drogadicción Materna","Ciertas  afecciones originadas  en el periodo perinatal");
        Add("Retardo  En El Crecimiento Fetal Y Desnutrición Fetal","Ciertas  afecciones originadas  en el periodo perinatal");
        Add("Trastornos Relacionados Con Duración  Corta De La Gestación Y Con Bajo Peso Al Nacer,  No Clasificados En Otra Parte","Ciertas  afecciones originadas  en el periodo perinatal");
        Add("Trastornos Relacionados Con El Embarazo Prolongado Y Con Sobrepeso  Al Nacer","Ciertas  afecciones originadas  en el periodo perinatal");
        Add("Hemorragia Y Laceración Intracraneal Debidas A Traumatismo Del Nacimiento","Ciertas  afecciones originadas  en el periodo perinatal");
        Add("Otros Traumatismos Del Nacimiento En El Sistema Nervioso Central","Ciertas  afecciones originadas  en el periodo perinatal");
        Add("Traumatismo Del Nacimiento En El Cuero Cabelludo  /(Incluye Cefalohematoma)","Ciertas  afecciones originadas  en el periodo perinatal");
        Add("Traumatismo Del Esqueleto Durante El Nacimiento","Ciertas  afecciones originadas  en el periodo perinatal");
        Add("Traumatismo Del Sistema Nervioso Periférico  Durante El Nacimiento","Ciertas  afecciones originadas  en el periodo perinatal");
        Add("Otros Traumatismos Del Nacimiento","Ciertas  afecciones originadas  en el periodo perinatal");
        Add("Hipoxia  Intrauterina","Ciertas  afecciones originadas  en el periodo perinatal");
        Add("Asfixia Al Nacimiento","Ciertas  afecciones originadas  en el periodo perinatal");
        Add("Dificultad  Respiratoria Del Recién Nacido","Ciertas  afecciones originadas  en el periodo perinatal");
        Add("Taquipnea Transitoria Del Recién Nacido","Ciertas  afecciones originadas  en el periodo perinatal");
        Add("Síndromes  De Aspiración  Neonatal","Ciertas  afecciones originadas  en el periodo perinatal");
        Add("Enfisema Intersticial Y Afecciones Relacionadas, Originadas  En El Período Perinatal","Ciertas  afecciones originadas  en el periodo perinatal");
        Add("Hemorragia Pulmonar Originada En El Periodo Perinatal","Ciertas  afecciones originadas  en el periodo perinatal");
        Add("Displasia Broncopulmonar Originada  En El Periodo Perinatal","Ciertas  afecciones originadas  en el periodo perinatal");
        Add("Otras Apneas Del Recién Nacido","Ciertas  afecciones originadas  en el periodo perinatal");
        Add("Sepsis Bacteriana Del Recién Nacido","Ciertas  afecciones originadas  en el periodo perinatal");
        Add("Onfalitis  Del Recién Nacido Con O Sin Hemorragia Leve","Ciertas  afecciones originadas  en el periodo perinatal");
        Add("Hemorragia Intracraneal No Traumática Del Feto Y Del Recién Nacido","Ciertas  afecciones originadas  en el periodo perinatal");
        Add("Enfermedad Hemorrágica Del Feto Y Del Recién Nacido","Ciertas  afecciones originadas  en el periodo perinatal");
        Add("Enfermedad Hemolítica Del Feto Y Del Recién Nacido","Ciertas  afecciones originadas  en el periodo perinatal");
        Add("Hidropesía Fetal Debida A Enfermedad Hemolítica","Ciertas  afecciones originadas  en el periodo perinatal");
        Add("Ictericia Neonatal Debida A Otras Hemólisis  Excesivas","Ciertas  afecciones originadas  en el periodo perinatal");
        Add("Ictericia Neonatal Por Otras Causas Y Las No Especificadas","Ciertas  afecciones originadas  en el periodo perinatal");
        Add("Coagulación Intravascular Diseminada En El Feto Y El Recién Nacido","Ciertas  afecciones originadas  en el periodo perinatal");
        Add("Policitemia  Neonatal","Ciertas  afecciones originadas  en el periodo perinatal");
        Add("Trastornos Transitorios Del Metabolismo Delos Carbohidratos Específicos Del Feto Y Del Recién Nacido","Ciertas  afecciones originadas  en el periodo perinatal");
        Add("Trastornos Neonatales Transitorios Del Metabolismo Del Calcio Y Del Magnesio","Ciertas  afecciones originadas  en el periodo perinatal");
        Add("Alteraciones Del Equilibrio  Del Sodio En El Recién Nacido","Ciertas  afecciones originadas  en el periodo perinatal");
        Add("Alteraciones Del Equilibrio  Del Potasio En El Recién Nacido","Ciertas  afecciones originadas  en el periodo perinatal");
        Add("Síndrome  Del Tapón  De Meconio","Ciertas  afecciones originadas  en el periodo perinatal");
        Add("Otras Peritonitis Neonatales","Ciertas  afecciones originadas  en el periodo perinatal");
        Add("Enterocolitis Necrotizante","Ciertas  afecciones originadas  en el periodo perinatal");
        Add("Convulsiones Del Recién Nacido","Ciertas  afecciones originadas  en el periodo perinatal");
        Add("Depresión Cerebral  Neonatal","Ciertas  afecciones originadas  en el periodo perinatal");
        Add("Encefalopatía Hipóxica Isquémica","Ciertas  afecciones originadas  en el periodo perinatal");
        Add("Anencefalia","Malformaciones congénitas, deformidades y anomalías cromosómicas");
        Add("Encefalocele","Malformaciones congénitas, deformidades y anomalías cromosómicas");
        Add("Estenosis Y Estrechez Congénitas Del Conducto Lagrimal","Malformaciones congénitas, deformidades y anomalías cromosómicas");
        Add("Catarata Congénita","Malformaciones congénitas, deformidades y anomalías cromosómicas");
        Add("Otras Malformaciones Congénitas Del Oído (Microtia, Macrotia, Oreja Supernumeraria, Otras Deformidades Del Pabellón Auricular, Anomalía  De La Posición De La Oreja, Oreja Prominente)","Malformaciones congénitas, deformidades y anomalías cromosómicas");
        Add("Seno, Fístula O Quiste De La Hendidura Branquial","Malformaciones congénitas, deformidades y anomalías cromosómicas");
        Add("Malformaciones Congénitas De La Nariz","Malformaciones congénitas, deformidades y anomalías cromosómicas");
        Add("Malformación Congénita De La Laringe (Incluye  Laringomalacia Congénita)","Malformaciones congénitas, deformidades y anomalías cromosómicas");
        Add("Malformaciones Congénitas De La Tráquea  Y De Los Bronquios","Malformaciones congénitas, deformidades y anomalías cromosómicas");
        Add("Malformaciones Congénitas Del Pulmón","Malformaciones congénitas, deformidades y anomalías cromosómicas");
        Add("Otras Malformaciones Congénitas Del Intestino (Incluye Divertículo De Meckel, Enfermedad De Hirschsprung Y Malrotación Intestinal)","Malformaciones congénitas, deformidades y anomalías cromosómicas");
        Add("Malformaciones Congénitas De Vesícula Biliar, Conductos  Biliares E Hígado (Incluye  Atresia De Conductos  Biliares Y Quiste De Colédoco)","Malformaciones congénitas, deformidades y anomalías cromosómicas");
        Add("Páncreas  Anular","Malformaciones congénitas, deformidades y anomalías cromosómicas");
        Add("Anquiloglosia","Malformaciones congénitas, deformidades y anomalías cromosómicas");
        Add("Síndrome  De Potter","Malformaciones congénitas, deformidades y anomalías cromosómicas");
        Add("Duplicación Del Uréter","Malformaciones congénitas, deformidades y anomalías cromosómicas");
        Add("Riñón Supernumerario","Malformaciones congénitas, deformidades y anomalías cromosómicas");
        Add("Riñón Ectópico","Malformaciones congénitas, deformidades y anomalías cromosómicas");
        Add("Malformación Del Uraco","Malformaciones congénitas, deformidades y anomalías cromosómicas");
        Add("Ausencia Congénita De La Vejiga Y De La Uretra","Malformaciones congénitas, deformidades y anomalías cromosómicas");
        Add("Polidactilia","Malformaciones congénitas, deformidades y anomalías cromosómicas");
        Add("Sindactilia","Malformaciones congénitas, deformidades y anomalías cromosómicas");
        Add("Craneosinostosis","Malformaciones congénitas, deformidades y anomalías cromosómicas");
        Add("Hernia Diafragmática Congénita","Malformaciones congénitas, deformidades y anomalías cromosómicas");
        Add("Ictiosis Congénita","Malformaciones congénitas, deformidades y anomalías cromosómicas");
        Add("Epidermólisis  Bullosa","Malformaciones congénitas, deformidades y anomalías cromosómicas");
        Add("Nevo No Neoplásico,  Congénito","Malformaciones congénitas, deformidades y anomalías cromosómicas");
        Add("Anormalidades Cromosómicas (Diagnóstico)","Malformaciones congénitas, deformidades y anomalías cromosómicas");
        Add("Choque  Hipovolémico","Síntomas  y signos generales");
        Add("Fractura  De La Bóveda Del Cráneo","Traumatismos, envenenamientos y algunas otras consecuencias de causas externas");
        Add("Traumatismo Intracraneal Con Coma Prolongado","Traumatismos, envenenamientos y algunas otras consecuencias de causas externas");
        Add("Avulsión Del Cuero Cabelludo","Traumatismos, envenenamientos y algunas otras consecuencias de causas externas");
        Add("Herida  Del Tórax","Traumatismos, envenenamientos y algunas otras consecuencias de causas externas");
        Add("Traumatismo Por Aplastamiento Del Pulgar Y Otro(S) Dedo(S)","Traumatismos, envenenamientos y algunas otras consecuencias de causas externas");
        Add("Quemaduras De Tercer  Grado De Las Diferentes Partes Del Cuerpo","Quemaduras y corrosiones");
        Add("Efectos Adversos De Drogas De Afectan  Primariamente El Sistema Nervioso Autónomo","Complicaciones de la atención médica y quirúrgica");
        Add("Efectos Adversos De Vacunas Bacterianas","Complicaciones de la atención médica y quirúrgica");
        Add("Atención  De Orificios Artificiales (Que Incluye Atención  De Traqueostomía, Gastrostomía, Ileostomía, Colostomía, Otros Orificios Artificiales  De Las Vías Digestivas, Cistostomía, Otros Orificios Artificiales  De Las Vías Urinarias Y Vagina Artificial)","Factores que influyen  en el estado de salud y contacto  con los servicios de salud");

        return causes;
    }
    
    private void Add(String intervencion, String tipo){
        Causes c = new Causes();
        c.intervencion = intervencion;
        c.tipo = tipo;
        causes.add(c);
    }

    public ArrayList<String> GetIntervencionesCauses(){

        AddIntervenciones("Vacunación Contra Tuberculosis (B.C.G.)");
        AddIntervenciones("Vacunación Contra Hepatitis B (H.B.)");
        AddIntervenciones("Administración De Vacuna Pentavalente (Dpt,  Hb, Hib)");
        AddIntervenciones("Vacunación Contra Rotavirus");
        AddIntervenciones("Vacunación Contra Neumococo Conjugado (Heptavalente)");
        AddIntervenciones("Vacunación Profiláctica Contra Influenza (Gripe Estacional) Menores De 14 Años Y Grupos De Riesgo");
        AddIntervenciones("Vacunación Contra Sarampión,  Parotiditis Y Rubéola (Srp)");
        AddIntervenciones("Vacunación Contra Difteria, Tosferina Y Tétanos (Dpt)");
        AddIntervenciones("Vacunación Contra Poliomielitis (Sabin)");
        AddIntervenciones("Vacunación Contra El Virus Del Papiloma Humano (Vph)");
        AddIntervenciones("Vacunación Contra Hepatitis B (Hb) Mayores De 14 Años");
        AddIntervenciones("Vacunación Contra Sarampión  Y Rubéola (Sr)");
        AddIntervenciones("Vacunación Contra Tétanos Y Difteria (Td)");
        AddIntervenciones("Vacunación Contra El Neumococo Para El Adulto  Mayor");
        AddIntervenciones("Vacunación Profiláctica Contra Influenza (Gripe Estacional) Para Mayores De 60 Años Sin Patologías Asociadas");
        AddIntervenciones("Acciones  Preventivas Para Recién Nacido");
        AddIntervenciones("Acciones  Preventivas Para Menores De 5 Años");
        AddIntervenciones("Acciones  Preventivas Para Niñas Y Niños  De 5 A 9 Años");
        AddIntervenciones("Detección Precoz De Los Trastornos De La Conducta Alimentaria");
        AddIntervenciones("Acciones  Preventivas Para Adolescentes De 10 A 19 Años");
        AddIntervenciones("Acciones  Preventivas Para Mujeres De 20 A 59 Años");
        AddIntervenciones("Acciones  Preventivas Para Hombres De 20 A 59 Años");
        AddIntervenciones("Examen Médico  Completo  Para Mujeres De 40 A 59 Años");
        AddIntervenciones("Examen Médico  Completo  Para Hombres De 40 A 59 Años");
        AddIntervenciones("Prevención Y Atención A Violencia Familiar Y De Género");
        AddIntervenciones("Acciones  Preventivas Para Adultos Mayores De 60 Años En Adelante");
        AddIntervenciones("Otras Acciones  De Promoción A La Salud Y Prevención  De Riesgos");
        AddIntervenciones("Diagnóstico Y Tratamiento De Anemia Ferropriva Y Por Deficiencia  De Vitamina B12");
        AddIntervenciones("Diagnóstico Y Tratamiento Por Deficiencia  De Vitamina A");
        AddIntervenciones("Diagnóstico Y Tratamiento De Escarlatina");
        AddIntervenciones("Diagnóstico Y Tratamiento De Sarampión,  Rubéola Y Parotiditis");
        AddIntervenciones("Diagnóstico Y Tratamiento De Varicela");
        AddIntervenciones("Diagnóstico Y Tratamiento De Faringoamigdalitis Aguda");
        AddIntervenciones("Diagnóstico Y Tratamiento De Tos Ferina");
        AddIntervenciones("Diagnóstico Y Tratamiento De Otitis Media No Supurativa");
        AddIntervenciones("Diagnóstico Y Tratamiento De Rinofaringitis Aguda");
        AddIntervenciones("Diagnóstico Y Tratamiento De Conjuntivitis");
        AddIntervenciones("Diagnóstico Y Tratamiento De Rinitis Alérgica Y Vasomotora");
        AddIntervenciones("Diagnóstico Y Tratamiento De Dengue Clásico (Y Otras Fiebres Producidas Por Flavivirus Y Arbovirus)");
        AddIntervenciones("Diagnóstico Y Tratamiento Del Síndrome  Diarreico  Agudo");
        AddIntervenciones("Diagnóstico Y Tratamiento De Fiebre Paratifoidea  Y Otras Salmonelosis");
        AddIntervenciones("Diagnóstico Y Tratamiento De Fiebre Tifoidea");
        AddIntervenciones("Diagnóstico Y Tratamiento Del Herpes Zóster");
        AddIntervenciones("Diagnóstico Y Tratamiento De Candidiasis Oral");
        AddIntervenciones("Diagnóstico Y Tratamiento De Gonorrea");
        AddIntervenciones("Diagnóstico Y Tratamiento De Infecciones Por Chlamydia  (Incluye Tracoma)");
        AddIntervenciones("Diagnóstico Y Tratamiento De Trichomoniasis");
        AddIntervenciones("Diagnóstico Y Tratamiento De Sífilis Precoz Y Tardía");
        AddIntervenciones("Diagnóstico Y Tratamiento De Cistitis");
        AddIntervenciones("Diagnóstico Y Tratamiento De Vaginitis  Aguda");
        AddIntervenciones("Diagnóstico Y Tratamiento De Vulvitis Aguda");
        AddIntervenciones("Diagnóstico Y Tratamiento De Chancro Blando");
        AddIntervenciones("Diagnóstico Y Tratamiento De Herpes Genital");
        AddIntervenciones("Diagnóstico Y Tratamiento De Amebiasis");
        AddIntervenciones("Diagnóstico Y Tratamiento De Anquilostomiasis Y Necatoriasis");
        AddIntervenciones("Diagnóstico Y Tratamiento De Ascariasis");
        AddIntervenciones("Diagnóstico Y Tratamiento De Enterobiasis");
        AddIntervenciones("Diagnóstico Y Tratamiento Farmacológico De Equinococosis");
        AddIntervenciones("Diagnóstico Y Tratamiento Farmacológico De Esquistosomiasis");
        AddIntervenciones("Diagnóstico Y Tratamiento Farmacológico De Estrongiloidiasis");
        AddIntervenciones("Diagnóstico Y Tratamiento Farmacológico De Filariasis");
        AddIntervenciones("Diagnóstico Y Tratamiento Farmacológico De Giardiasis");
        AddIntervenciones("Diagnóstico Y Tratamiento Farmacológico De Teniasis");
        AddIntervenciones("Diagnóstico Y Tratamiento Farmacológico De Tricuriasis");
        AddIntervenciones("Diagnóstico Y Tratamiento Farmacológico De Triquinosis");
        AddIntervenciones("Diagnóstico Y Tratamiento Farmacológico De Brucelosis");
        AddIntervenciones("Diagnóstico Y Tratamiento De Escabiosis");
        AddIntervenciones("Diagnóstico Y Tratamiento De Pediculosis Y Phthiriasis");
        AddIntervenciones("Diagnóstico Y Tratamiento De Micosis Superficiales (Excepto Onicomicosis)");
        AddIntervenciones("Diagnóstico Y Tratamiento De Onicomicosis");
        AddIntervenciones("Diagnóstico Y Tratamiento De Erisipela Y Celulitis");
        AddIntervenciones("Diagnóstico Y Tratamiento De Procesos Infecciosos De Rezago (Paludismo, Ricketsiosis, Lepra, Enfermedad De Chagas,  Leishmaniasis, Oncocercosis)");
        AddIntervenciones("Diagnóstico Y Tratamiento De Dermatitis Alérgica Y De Contacto");
        AddIntervenciones("Diagnóstico Y Tratamiento De Dermatitis Atópica");
        AddIntervenciones("Diagnóstico Y Tratamiento De Dermatitis De Contacto Por Irritantes");
        AddIntervenciones("Diagnóstico Y Tratamiento De Dermatitis Del Pañal");
        AddIntervenciones("Diagnóstico Y Tratamiento De Dermatitis Exfoliativa");
        AddIntervenciones("Diagnóstico Y Tratamiento De Dermatitis Seborreica");
        AddIntervenciones("Diagnóstico Y Tratamiento De Verrugas Vulgares");
        AddIntervenciones("Diagnóstico Y Tratamiento Del Acné");
        AddIntervenciones("Diagnóstico Y Tratamiento De Infección Aguda  Por Virus De La Hepatitis A Y B");
        AddIntervenciones("Diagnóstico Y Tratamiento De Gastritis Aguda,  Duodenitis Y Dispepsia");
        AddIntervenciones("Diagnóstico Y Tratamiento Del Síndrome  De Intestino Irritable");
        AddIntervenciones("Diagnóstico Y Tratamiento De Prediabetes Y Diabetes Mellitus Tipo 2");
        AddIntervenciones("Diagnóstico Y Tratamiento De Hipertensión Arterial");
        AddIntervenciones("Diagnóstico Y Tratamiento Conservador De Artrosis Erosiva Y Poliartrosis No Especificada");
        AddIntervenciones("Diagnóstico Y Tratamiento De Lumbalgia");
        AddIntervenciones("Atención Por Algunos  Signos,  Síntomas Y Otros Factores Que Influyen En El Estado De Salud");
        AddIntervenciones("Manejo  Ambulatorio  De Cuidados Paliativos Y Dolor Crónico");
        AddIntervenciones("Método De Planificación Familiar Temporal Con  Anticonceptivos Hormonales");
        AddIntervenciones("Consejo Y Asesoramiento  General Sobre Anticoncepción Mediante El Uso Del Condón");
        AddIntervenciones("Método De Planificación Familiar Temporal Con  Dispositivo  Intrauterino");
        AddIntervenciones("Atención Prenatal En El Embarazo");
        AddIntervenciones("Diagnóstico Y Tratamiento De Trastorno Por Déficit De Atención Con  Componente Hiperactivo");
        AddIntervenciones("Diagnóstico Y Tratamiento De Autismo  Y Síndrome  De Asperger");
        AddIntervenciones("Diagnóstico Y Tratamiento De Dismenorrea Primaria");
        AddIntervenciones("Diagnóstico Y Tratamiento Del Climaterio  Y Menopausia");
        AddIntervenciones("Diagnóstico Y Tratamiento De Trastornos Benignos De La Mama");
        AddIntervenciones("Diagnóstico Y Tratamiento De Hiperplasia Endometrial");
        AddIntervenciones("Diagnóstico Y Tratamiento De Vaginitis  Subaguda Y Crónica");
        AddIntervenciones("Diagnóstico Y Tratamiento De Endometriosis");
        AddIntervenciones("Diagnóstico Y Tratamiento De Uretritis Y Síndrome  Uretral");
        AddIntervenciones("Diagnóstico Y Tratamiento De Lesiones Escamosas Intraepiteliales De Grados Bajo Y Moderado");
        AddIntervenciones("Diagnóstico Y Tratamiento De Lesiones Escamosas Intraepiteliales De Alto Grado");
        AddIntervenciones("Diagnóstico Y Tratamiento De Desnutrición Leve, Moderada  Y Severa");
        AddIntervenciones("Diagnóstico Y Tratamiento De Desnutrición Severa Tipo Kwashiorkor");
        AddIntervenciones("Diagnóstico Y Tratamiento De Desnutrición Severa Tipo Marasmo");
        AddIntervenciones("Diagnóstico Y Tratamiento De Secuelas De Desnutrición");
        AddIntervenciones("Diagnóstico Y Tratamiento Médico  Del Sobrepeso Y Obesidad Exógena");
        AddIntervenciones("Diagnóstico Y Tratamiento De Laringotraqueítis Aguda");
        AddIntervenciones("Diagnóstico Y Tratamiento De Otitis Media Supurativa");
        AddIntervenciones("Diagnóstico Y Tratamiento De Sinusitis Aguda");
        AddIntervenciones("Diagnóstico Y Tratamiento Del Asma Y Sus Exacerbaciones En Adultos");
        AddIntervenciones("Diagnóstico Y Tratamiento Del Asma Y Sus Exacerbaciones En Menores De 18 Años");
        AddIntervenciones("Diagnóstico Y Tratamiento De Tuberculosis (Taes)");
        AddIntervenciones("Diagnóstico Y Tratamiento De Tuberculosis Farmacorresistente (Taes)");
        AddIntervenciones("Diagnóstico Y Tratamiento De Psoriasis");
        AddIntervenciones("Diagnóstico Y Tratamiento De Esofagitis Por Reflujo");
        AddIntervenciones("Diagnóstico Y Tratamiento De Úlcera Gástrica Y Péptica Crónica No Perforada");
        AddIntervenciones("Diagnóstico Y Tratamiento De Dislipidemia");
        AddIntervenciones("Diagnóstico Y Tratamiento De Hipertiroidismo");
        AddIntervenciones("Diagnóstico Y Tratamiento De Crisis Tirotóxica");
        AddIntervenciones("Diagnóstico Y Tratamiento De Hipotiroidismo");
        AddIntervenciones("Diagnóstico Y Tratamiento De Diabetes Mellitus Tipo 1");
        AddIntervenciones("Diagnóstico Y Tratamiento De Insuficiencia Cardiaca");
        AddIntervenciones("Diagnóstico Y Tratamiento De Osteoporosis");
        AddIntervenciones("Diagnóstico Y Tratamiento De Hiperuricemia Y Gota");
        AddIntervenciones("Diagnóstico Y Tratamiento De Artritis Reumatoide");
        AddIntervenciones("Diagnóstico Y Tratamiento De Trastornos Afectivos (Depresión,  Trastorno Afectivo De Tipo Bipolar, Trastornos Afectivos Persistentes)");
        AddIntervenciones("Diagnóstico Y Tratamiento De Trastornos De Ansiedad (Ansiedad  Generalizada, Trastornos De Pánico, Reacción A Estrés, Trastornos De Adaptación {Trastorno De Estrés Postraumático Y Trastorno Adaptativo})");
        AddIntervenciones("Diagnóstico Y Tratamiento De Trastornos Psicóticos (Esquizofrenia, Psicóticos Y Esquizotípico)");
        AddIntervenciones("Diagnóstico Y Tratamiento Ambulatorio  De Epilepsia Y Crisis Convulsivas");
        AddIntervenciones("Diagnóstico Y Tratamiento Médico  De Enfermedad De Parkinson");
        AddIntervenciones("Diagnóstico Y Tratamiento Conservador De Luxación Congénita De Cadera");
        AddIntervenciones("Rehabilitación De Fracturas");
        AddIntervenciones("Diagnóstico Y Tratamiento De Parálisis Facial");
        AddIntervenciones("Detección Temprana De Adicciones (Consejería)");
        AddIntervenciones("Prevención De Caries Dental");
        AddIntervenciones("Aplicación De Selladores De Fosetas Y Fisuras Dentales");
        AddIntervenciones("Restauraciones  Dentales Con  Amalgama, Ionómero De Vidrio Y Resina, Por Caries O Fractura De Los Dientes");
        AddIntervenciones("Diagnóstico Y Tratamiento De Focos Infecciosos Bacterianos Agudos  En La Cavidad  Bucal");
        AddIntervenciones("Extracción De Dientes Erupcionados Y Restos Radiculares");
        AddIntervenciones("Terapia Pulpar");
        AddIntervenciones("Extracción De Tercer Molar");
        AddIntervenciones("Estabilización En Urgencias");
        AddIntervenciones("Estabilización En Urgencias  Por Crisis Hipertensiva");
        AddIntervenciones("Diagnóstico Y Tratamiento De La Cetoacidosis Diabética");
        AddIntervenciones("Diagnóstico Y Tratamiento Del Síndrome  Hiperglucémico Hiperosmolar  No Cetósico");
        AddIntervenciones("Diagnóstico Y Tratamiento De Angina De Pecho");
        AddIntervenciones("Atención En Urgencias  Por Intoxicación Aguda,  Uso Nocivo Y Estado De Abstinencia De Sustancias Adictivas");
        AddIntervenciones("Diagnóstico Y Tratamiento Del Envenenamiento Por Fenotiazinas");
        AddIntervenciones("Diagnóstico Y Tratamiento Del Envenenamiento Por Álcalis, Cáusticos Y Sustancias Alcalinas Similares");
        AddIntervenciones("Diagnóstico Y Tratamiento Del Envenenamiento Por Salicilatos");
        AddIntervenciones("Diagnóstico Y Tratamiento Del Envenenamiento Por Metanol");
        AddIntervenciones("Diagnóstico Y Tratamiento Del Envenenamiento Por Insecticidas Organofosforados Y Carbamatos");
        AddIntervenciones("Diagnóstico Y Tratamiento Del Envenenamiento Por Monóxido De Carbono");
        AddIntervenciones("Diagnóstico Y Tratamiento Del Envenenamiento Por Mordedura De Serpiente");
        AddIntervenciones("Diagnóstico Y Tratamiento De Picadura  De Alacrán");
        AddIntervenciones("Diagnóstico Y Tratamiento De Picaduras De Abeja, Araña Y Otros Artrópodos");
        AddIntervenciones("Diagnóstico Y Tratamiento De Intoxicación Aguda  Alimentaria");
        AddIntervenciones("Manejo  De Mordedura Y Prevención  De Rabia En Humanos");
        AddIntervenciones("Extracción De Cuerpos Extraños");
        AddIntervenciones("Curación Y Suturas De Lesiones Traumáticas  De Tejidos Blandos");
        AddIntervenciones("Diagnóstico Y Tratamiento Del Traumatismo Craneoencefálico Leve");
        AddIntervenciones("Manejo  En Urgencias  De Quemaduras  De Primer Grado");
        AddIntervenciones("Diagnóstico Y Tratamiento De Esguince Cervical");
        AddIntervenciones("Diagnóstico Y Tratamiento De Esguince De Hombro");
        AddIntervenciones("Diagnóstico Y Tratamiento De Esguince De Codo");
        AddIntervenciones("Diagnóstico Y Tratamiento De Esguince De Muñeca Y Mano");
        AddIntervenciones("Diagnóstico Y Tratamiento Conservador De Esguince De Rodilla");
        AddIntervenciones("Diagnóstico Y Tratamiento De Esguince De Tobillo Y Pie");
        AddIntervenciones("Diagnóstico Y Tratamiento De Pielonefritis");
        AddIntervenciones("Diagnóstico Y Tratamiento De Bronquiolitis");
        AddIntervenciones("Diagnóstico Y Tratamiento De Bronquitis Aguda");
        AddIntervenciones("Diagnóstico Y Tratamiento De Meningitis Y Meningoencefalitis Agudas");
        AddIntervenciones("Diagnóstico Y Tratamiento De Mastoiditis");
        AddIntervenciones("Diagnóstico Y Tratamiento De Osteomielitis");
        AddIntervenciones("Diagnóstico Y Tratamiento De Neumonía En Menores De 18 Años");
        AddIntervenciones("Diagnóstico Y Tratamiento De Neumonía En Adultos");
        AddIntervenciones("Diagnóstico Y Tratamiento De Absceso Hepático Amebiano");
        AddIntervenciones("Diagnóstico Y Tratamiento De Enfermedad Pélvica Inflamatoria");
        AddIntervenciones("Diagnóstico Y Tratamiento De Amenaza De Aborto");
        AddIntervenciones("Diagnóstico Y Tratamiento De Amenaza De Parto Pretérmino");
        AddIntervenciones("Atención Del Parto Y Puerperio Fisiológico");
        AddIntervenciones("Diagnóstico Y Tratamiento De Pelviperitonitis");
        AddIntervenciones("Diagnóstico Y Tratamiento De Endometritis Puerperal");
        AddIntervenciones("Diagnóstico Y Tratamiento De Choque Séptico Puerperal");
        AddIntervenciones("Atención Del Recién Nacido");
        AddIntervenciones("Diagnóstico De Ictericia  Neonatal");
        AddIntervenciones("Diagnóstico Y Tratamiento Del Recién Nacido Pretérmino  Sin Complicaciones");
        AddIntervenciones("Diagnóstico Y Tratamiento Del Recién Nacido Pretérmino  Con  Hipotermia");
        AddIntervenciones("Diagnóstico Y Tratamiento Del Pretérmino  Con  Bajo Peso Al Nacer");
        AddIntervenciones("Diagnóstico Y Tratamiento De Preeclampsia Leve Y Moderada");
        AddIntervenciones("Diagnóstico Y Tratamiento De Preeclampsia Severa");
        AddIntervenciones("Diagnóstico Y Tratamiento De Eclampsia");
        AddIntervenciones("Diagnóstico Y Tratamiento De Hemorragia Obstétrica Puerperal (Incluye Choque Hipovolémico)");
        AddIntervenciones("Diagnóstico Y Tratamiento De Hemorragia Por Placenta Previa Y Desprendimiento Prematuro  De Placenta Normoinserta");
        AddIntervenciones("Diagnóstico Y Tratamiento De Infección De Episiorrafia O Herida Quirúrgica Obstétrica");
        AddIntervenciones("Diagnóstico Y Tratamiento De Litiasis Renal Y Ureteral");
        AddIntervenciones("Diagnóstico Y Tratamiento De Litiasis De Vías Urinarias Inferiores");
        AddIntervenciones("Diagnóstico Y Tratamiento Del Síndrome  Escrotal Agudo");
        AddIntervenciones("Diagnóstico Y Tratamiento De Retención Aguda  De Orina");
        AddIntervenciones("Diagnóstico Y Tratamiento De Prostatitis Aguda");
        AddIntervenciones("Diagnóstico Y Tratamiento De Dengue Hemorrágico (Y Otras Complicaciones Por Flavivirus)");
        AddIntervenciones("Diagnóstico Y Tratamiento De Traumatismo Craneoencefálico Moderado");
        AddIntervenciones("Diagnóstico Y Tratamiento Conservador De Pancreatitis  Aguda");
        AddIntervenciones("Diagnóstico Y Tratamiento Hospitalario Del Estatus Epiléptico Y Crisis Convulsivas De Difícil Control");
        AddIntervenciones("Tratamiento Hospitalario De Hipertensión Arterial");
        AddIntervenciones("Diagnóstico Y Tratamiento De Insuficiencia Cardiaca  Aguda  Y Del Edema Agudo Pulmonar");
        AddIntervenciones("Diagnóstico Y Tratamiento De Enfermedad Pulmonar  Obstructiva  Crónica");
        AddIntervenciones("Diagnóstico Y Tratamiento De Neuropatía Periférica Secundaria  A Diabetes");
        AddIntervenciones("Tratamiento Hospitalario De Úlcera Y Del Pie Diabético Infectados");
        AddIntervenciones("Diagnóstico Y Tratamiento Hospitalario De Quemaduras  De Segundo Grado");
        AddIntervenciones("Diagnóstico Y Tratamiento De Hemorragia Digestiva");
        AddIntervenciones("Diagnóstico Y Tratamiento Del Síndrome  De Hellp");
        AddIntervenciones("Diagnóstico Y Tratamiento De Corioamnioítis");
        AddIntervenciones("Diagnóstico Y Tratamiento De Embolia Obstétrica");
        AddIntervenciones("Diagnóstico Y Tratamiento De Diabetes Gestacional");
        AddIntervenciones("Diagnóstico Y Tratamiento De Hipertensión Inducida Y/O Preexistente En El Embarazo");
        AddIntervenciones("Diagnóstico Y Tratamiento De Trombosis Venosa Profunda En El Embarazo Y Puerperio");
        AddIntervenciones("Laparotomía Exploradora");
        AddIntervenciones("Diagnóstico Y Tratamiento De Apendicitis");
        AddIntervenciones("Esplenectomía");
        AddIntervenciones("Diagnóstico Y Tratamiento De Enfermedad Diverticular");
        AddIntervenciones("Diagnóstico Y Tratamiento Quirúrgico De Isquemia E Infarto  Intestinal");
        AddIntervenciones("Diagnóstico Y Tratamiento De Obstrucción Intestinal E Ileo");
        AddIntervenciones("Diagnóstico Y Tratamiento Quirúrgico De Perforación Gástrica Y/O Intestinal");
        AddIntervenciones("Diagnóstico Y Tratamiento Del Vólvulo");
        AddIntervenciones("Diagnóstico Y Tratamiento Del Absceso Perirrectal");
        AddIntervenciones("Diagnóstico Y Tratamiento De Fístula Y/O La Fisura Anal");
        AddIntervenciones("Diagnóstico Y Tratamiento De Enfermedad Hemorroidal");
        AddIntervenciones("Diagnóstico Y Tratamiento De Hernia Hiatal");
        AddIntervenciones("Diagnóstico Y Tratamiento De Hipertrofia Congénita Del Píloro");
        AddIntervenciones("Diagnóstico Y Tratamiento De Hernia Crural");
        AddIntervenciones("Diagnóstico Y Tratamiento De Hernia Inguinal");
        AddIntervenciones("Diagnóstico Y Tratamiento De Hernia Umbilical");
        AddIntervenciones("Diagnóstico Y Tratamiento De Hernia Ventral");
        AddIntervenciones("Diagnóstico Y Tratamiento De Colecistitis  Y Colelitiasis");
        AddIntervenciones("Diagnóstico Y Tratamiento Quirúrgico De Los Condilomas");
        AddIntervenciones("Diagnóstico Y Tratamiento De Quistes De Ovario");
        AddIntervenciones("Diagnóstico Y Tratamiento De Torsión De Anexos");
        AddIntervenciones("Método Definitivo De Planificación Familiar En La Mujer (Oclusión Tubaria Bilateral)");
        AddIntervenciones("Diagnóstico Y Tratamiento Quirúrgico De Enfermedad Trofoblástica");
        AddIntervenciones("Diagnóstico Y Tratamiento Quirúrgico Del Embarazo Ectópico");
        AddIntervenciones("Diagnóstico Y Tratamiento Del Aborto Incompleto (No  Incluye Interrupción Legal Del Embarazo)");
        AddIntervenciones("Atención De Cesárea Y Puerperio Quirúrgico");
        AddIntervenciones("Reparación  Uterina");
        AddIntervenciones("Ablación Endometrial");
        AddIntervenciones("Tratamiento Laparoscópico De La Endometriosis");
        AddIntervenciones("Diagnóstico Y Tratamiento De Miomatosis  Uterina");
        AddIntervenciones("Histerectomía Abdominal Y Vaginal");
        AddIntervenciones("Diagnóstico Y Tratamiento Del Prolapso Genital Femenino (Colpoperineoplastía)");
        AddIntervenciones("Método Definitivo De Planificación Familiar En Hombres (Vasectomía)");
        AddIntervenciones("Circuncisión");
        AddIntervenciones("Orquidopexia");
        AddIntervenciones("Diagnóstico Y Tratamiento De Hiperplasia De La Próstata");
        AddIntervenciones("Extirpación De Lesión Cancerosa  De Piel (No  Incluye Melanoma)");
        AddIntervenciones("Extirpación De Tumor  Benigno  En Tejidos Blandos");
        AddIntervenciones("Amigdalectomía Con  O Sin Adenoidectomía");
        AddIntervenciones("Tratamiento Quirúrgico De Papiloma Faríngeo  (Incluye Papiloma Laríngeo)");
        AddIntervenciones("Reparación  De Labio Hendido Con  O Sin Paladar Hendido");
        AddIntervenciones("Cirugía  De Acortamiento Muscular Para Estrabismo");
        AddIntervenciones("Cirugía  De Alargamiento Muscular Para Estrabismo");
        AddIntervenciones("Tratamiento Quirúrgico De Glaucoma");
        AddIntervenciones("Tratamiento Quirúrgico De Pterigión");
        AddIntervenciones("Tratamiento Quirúrgico De Hidrocefalia");
        AddIntervenciones("Colocación Y Retiro De Diversos Catéteres");
        AddIntervenciones("Disección Radical De Cuello");
        AddIntervenciones("Toracotomía, Pleurotomía  Y Drenaje De Tórax");
        AddIntervenciones("Tratamiento Quirúrgico De Luxación Congénita De Cadera");
        AddIntervenciones("Tratamiento Quirúrgico De Pie Equino En Niños");
        AddIntervenciones("Safenectomía");
        AddIntervenciones("Reducción De Luxaciones Bajo Anestesia Por Manipulación");
        AddIntervenciones("Reducción Quirúrgica De Fractura De Clavícula");
        AddIntervenciones("Reducción Quirúrgica De Fractura De Húmero");
        AddIntervenciones("Reducción Quirúrgica De Fractura De Cúbito Y Radio");
        AddIntervenciones("Reducción Quirúrgica De Fractura De Mano");
        AddIntervenciones("Reducción Quirúrgica De Fractura De Cadera");
        AddIntervenciones("Reducción Quirúrgica De Fractura De Fémur");
        AddIntervenciones("Reducción Quirúrgica De Fractura De Tibia Y Peroné");
        AddIntervenciones("Reducción Quirúrgica De Fractura De Tobillo Y Pie");
        AddIntervenciones("Tratamiento Artroscópico De Las Lesiones De La Rodilla");
        AddIntervenciones("Artroplastía Total De Rodilla");
        AddIntervenciones("Amputación De Miembro Inferior Secundaria  A Pie Diabético");
        AddIntervenciones("Tratamiento De Quiste Sinovial Y Ganglión");
        AddIntervenciones("Diagnóstico Y Tratamiento De Arritmias Cardiacas");
        AddIntervenciones("Diagnóstico Y Tratamiento Quirúrgico De Cataratas");

        return intervenciones;
    }

    public ArrayList<String> GetIntervencionesGastosCatastroficos(){

        AddIntervenciones("Peso Extremadamente Bajo Al Nacer");
        AddIntervenciones("Síndrome  De Dificultad  Respiratoria Del Recién Nacido");
        AddIntervenciones("Sepsis Del Recién Nacido Debida A Estreptococo Del Grupo B");
        AddIntervenciones("Atresia Anal");
        AddIntervenciones("Atresia Esofágica");
        AddIntervenciones("Atresia Intestinal");
        AddIntervenciones("Onfalocele");
        AddIntervenciones("Gastrosquisis");
        AddIntervenciones("Atresia-Estenosis Duodenal");
        AddIntervenciones("Espina Bífida");
        AddIntervenciones("Estenosis Ureteral");
        AddIntervenciones("Estenosis Del Meato Uretral");
        AddIntervenciones("Estenosis Ureteral");
        AddIntervenciones("Extrofia Vesical");
        AddIntervenciones("Hipoplasia/Displasia Renal");
        AddIntervenciones("Hipospadias-Epispadias");
        AddIntervenciones("Uréter  Retrocavo");
        AddIntervenciones("Ureterocele");
        AddIntervenciones("Estenosis Uretral");
        AddIntervenciones("Uréter  Éctópico (Meatos  Ectópicos)");
        AddIntervenciones("Malformaciones Congénitas Cardiacas");
        AddIntervenciones("Deficiencia  Del Factor Viii");
        AddIntervenciones("Deficiencia  Del Factor Ix");
        AddIntervenciones("Enfermedad De Von Willebrand");
        AddIntervenciones("Enfermedad De Fabry / Enfermedad De Gaucher");
        AddIntervenciones("Mucopolisacaridosis Tipo I");
        AddIntervenciones("Mucopolisacaridosis Tipo Ii");
        AddIntervenciones("Mucopolisacaridosis Tipo Vi");
        AddIntervenciones("Enfermedad De Pompe");
        AddIntervenciones("Astrocitoma");
        AddIntervenciones("Ependimoma");
        AddIntervenciones("Meduloblastoma");
        AddIntervenciones("Neuroblastoma");
        AddIntervenciones("Otros Tumores Del Snc*");
        AddIntervenciones("Tumor  De Wilms");
        AddIntervenciones("Otros Tumores Renales*");
        AddIntervenciones("Leucemia Linfoblástica  Aguda");
        AddIntervenciones("Leucemia Mieloblástica  Aguda");
        AddIntervenciones("Leucemias Crónicas");
        AddIntervenciones("Síndromes  Mielodisplásicos");
        AddIntervenciones("Hepatocarcinoma");
        AddIntervenciones("Hepatoblastoma");
        AddIntervenciones("Osteosarcoma");
        AddIntervenciones("Sarcoma De Ewing");
        AddIntervenciones("Linfoma No Hodgkin");
        AddIntervenciones("Enfermedad O Linfoma De Hodgkin");
        AddIntervenciones("Retinoblastoma");
        AddIntervenciones("Sarcoma De Partes Blandas");
        AddIntervenciones("Tumores Gonadales Y Extragonadales");
        AddIntervenciones("Tumores Extragonadales");
        AddIntervenciones("Diversos Carcinomas*");
        AddIntervenciones("Histiocitosis Maligna");
        AddIntervenciones("Tumor  Maligno De Ovario");
        AddIntervenciones("Tumor  Maligno De Próstata");
        AddIntervenciones("Seminoma Y No Seminoma");
        AddIntervenciones("Cáncer  Cervicouterino");
        AddIntervenciones("Cáncer  De Mama");
        AddIntervenciones("Tumor  Maligno De Colon");
        AddIntervenciones("Tumor  Maligno De La Unión  Recto Sigmoidea");
        AddIntervenciones("Tumor  Maligno De Recto");
        AddIntervenciones("Folicular");
        AddIntervenciones("Difuso");
        AddIntervenciones("Infarto  Agudo Al Miocardio");
        AddIntervenciones("Hepatitis Viral Tipo C Crónica");
        AddIntervenciones("Trasplante De Cornea");
        AddIntervenciones("Trasplante De Medula  Ósea Menores De 18 Años");
        AddIntervenciones("Trasplante Renal Menores De 18 Años");
        AddIntervenciones("Síndrome  De Turner");

        return intervenciones;
    }

    public ArrayList<String> GetIntervencionesSeguroMedico(){

        AddIntervenciones("Tuberculosis Del Sistema Nervioso");
        AddIntervenciones("Tuberculosis Miliar");
        AddIntervenciones("Listeriosis");
        AddIntervenciones("Tétanos  Neonatal");
        AddIntervenciones("Septicemia  No Especificada (Incluye  Choque Séptico)");
        AddIntervenciones("Sífilis Congénita");
        AddIntervenciones("Encefalitis Viral, No Especificada");
        AddIntervenciones("Enfermedad Debida A Virus Citomegálico");
        AddIntervenciones("Toxoplasmosis");
        AddIntervenciones("Tumor  Benigno  De Las Glándulas Salivales Mayores (Ránula)");
        AddIntervenciones("Tumor  Benigno  Del Mediastino");
        AddIntervenciones("Tumor  Benigno  De La Piel Del Labio");
        AddIntervenciones("Tumor  Benigno  Del Ojo Y Sus Anexos");
        AddIntervenciones("Púrpura  Trombocitopénica Idiopática");
        AddIntervenciones("Inmunodeficiencia Con Predominio De Defectos De Los Anticuerpos");
        AddIntervenciones("Inmunodeficiencias Combinadas");
        AddIntervenciones("Otras Inmunodeficiencias");
        AddIntervenciones("Intolerancia A La Lactosa");
        AddIntervenciones("Fibrosis Quística");
        AddIntervenciones("Depleción Del Volumen");
        AddIntervenciones("Hiperplasia Congénita De Glándulas  Suprarrenales,");
        AddIntervenciones("Fenilcetonuria");
        AddIntervenciones("Galactosemia");
        AddIntervenciones("Otros Trastornos Del Nervio Facial");
        AddIntervenciones("Síndrome  De Guillain-Barré");
        AddIntervenciones("Parálisis Cerebral  Infantil (Diagnóstico, Terapia  Y En Su Caso, Los Insumos  O Medicamentos Especializados  Utilizados;  Anual Y Hasta Por 5 Años).");
        AddIntervenciones("Hemiplejía (Diagnóstico, Terapia  Y En Su Caso, Los Insumos  O Medicamentos Especializados Utilizados;  Anual Y Hasta Por 5 Años).");
        AddIntervenciones("Paraplejía Y Cuadriplejía (Diagnóstico, Terapia  Y En Su Caso, Los Insumos  O Medicamentos Especializados  Utilizados;  Anual Y Hasta Por 5 Años).");
        AddIntervenciones("Retinopatía De La Prematuridad");
        AddIntervenciones("Hipoacusia Neurosensorial Bilateral (Prótesis  Auditiva Externa Y Sesiones De Rehabilitación Auditiva Verbal)");
        AddIntervenciones("Habilitación Auditiva Verbal En Niños No Candidatos A Implantación De Prótesis De Cóclea (Anual  Hasta Por 5 Años)");
        AddIntervenciones("Implantación Prótesis Cóclea");
        AddIntervenciones("Habilitación Auditiva Verbal (Anual  Hasta Por 5 Años).");
        AddIntervenciones("Miocarditis  Aguda");
        AddIntervenciones("Fibroelastosis  Endocárdica");
        AddIntervenciones("Hipertensión Pulmonar Primaria");
        AddIntervenciones("Neumonía Por Influenza Por Virus Identificado");
        AddIntervenciones("Neumonía Por Influenza Por Virus No Identificado");
        AddIntervenciones("Neumonía Bacteriana No Clasificada En Otra Parte");
        AddIntervenciones("Bronconeumonía, No Especificada");
        AddIntervenciones("Neumonitis Debida A Sólidos Y Líquidos");
        AddIntervenciones("Piotórax");
        AddIntervenciones("Derrame Pleural No Clasificado En Otra Parte");
        AddIntervenciones("Derrame Pleural En Afecciones Clasificadas En Otra Parte");
        AddIntervenciones("Neumotórax");
        AddIntervenciones("Otros Trastornos Respiratorios (Incluye  Enfermedades De La Tráquea  Y De Los Bronquios, No Clasificadas En Otra Parte,  Colapso Pulmonar, Enfisema Intersticial, Enfisema Compensatorio, Otros Trastornos Del Pulmón, Enfermedades Del Mediastino, No Clasificadas En Otra Parte, Trastornos Del Diafragma, Otros Trastornos Respiratorios Especificados)");
        AddIntervenciones("Trastornos Del Desarrollo  Y De La Erupción  De Los Dientes");
        AddIntervenciones("Estomatitis Y Lesiones Afines");
        AddIntervenciones("Otras Enfermedades Del Esófago (Incluye  Acalasia Del Cardias, Úlcera Del Esófago, Obstrucción Del Esófago, Perforación Del Esófago, Disquinesia Del Esófago, Divertículo Del Esófago, Adquirido, Síndrome  De Laceración Y Hemorragia Gastroesofágicas, Otras Enfermedades Especificadas Del Esófago, Enfermedad Del Esófago, No Especificada)");
        AddIntervenciones("Constipación");
        AddIntervenciones("Malabsorción Intestinal");
        AddIntervenciones("Otros Trastornos Del Sistema Digestivo Consecutivos  A Procedimientos, No Clasificados En Otra Parte");
        AddIntervenciones("Síndrome  Estafilocócico De La Piel Escaldada (Síndrome De Ritter)");
        AddIntervenciones("Absceso Cutáneo, Furúnculo Y Carbunco");
        AddIntervenciones("Quiste  Epidérmico");
        AddIntervenciones("Artritis  Piógena");
        AddIntervenciones("Artritis  Juvenil");
        AddIntervenciones("Poliarteritis Nodosa Y Afecciones Relacionadas");
        AddIntervenciones("Fascitis Necrotizante");
        AddIntervenciones("Síndrome  Nefrítico  Agudo");
        AddIntervenciones("Síndrome  Nefrótico, Anomalía Glomerular Mínima");
        AddIntervenciones("Uropatía  Obstructiva Y Por Reflujo");
        AddIntervenciones("Insuficiencia Renal Aguda");
        AddIntervenciones("Insuficiencia Renal Terminal");
        AddIntervenciones("Divertículo De La Vejiga");
        AddIntervenciones("Infección  De Vías Urinarias, Sitio No Especificado");
        AddIntervenciones("Hidrocele Y Espermatocele");
        AddIntervenciones("Orquitis Y Epididimitis");
        AddIntervenciones("Fístula Vesicovaginal");
        AddIntervenciones("Feto Y Recién Nacido Afectados Por Trastornos Hipertensivos De La Madre");
        AddIntervenciones("Feto Y Recién Nacido Afectados Por Ruptura Prematura De Membranas");
        AddIntervenciones("Feto Y Recién Nacido Afectado Por Complicaciones De La Placenta, Del Cordón Umbilical  Y De Las Membranas");
        AddIntervenciones("Feto Y Recién Nacido Afectados Por Drogadicción Materna");
        AddIntervenciones("Retardo  En El Crecimiento Fetal Y Desnutrición Fetal");
        AddIntervenciones("Trastornos Relacionados Con Duración  Corta De La Gestación Y Con Bajo Peso Al Nacer,  No Clasificados En Otra Parte");
        AddIntervenciones("Trastornos Relacionados Con El Embarazo Prolongado Y Con Sobrepeso  Al Nacer");
        AddIntervenciones("Hemorragia Y Laceración Intracraneal Debidas A Traumatismo Del Nacimiento");
        AddIntervenciones("Otros Traumatismos Del Nacimiento En El Sistema Nervioso Central");
        AddIntervenciones("Traumatismo Del Nacimiento En El Cuero Cabelludo  /(Incluye Cefalohematoma)");
        AddIntervenciones("Traumatismo Del Esqueleto Durante El Nacimiento");
        AddIntervenciones("Traumatismo Del Sistema Nervioso Periférico  Durante El Nacimiento");
        AddIntervenciones("Otros Traumatismos Del Nacimiento");
        AddIntervenciones("Hipoxia  Intrauterina");
        AddIntervenciones("Asfixia Al Nacimiento");
        AddIntervenciones("Dificultad  Respiratoria Del Recién Nacido");
        AddIntervenciones("Taquipnea Transitoria Del Recién Nacido");
        AddIntervenciones("Síndromes  De Aspiración  Neonatal");
        AddIntervenciones("Enfisema Intersticial Y Afecciones Relacionadas, Originadas  En El Período Perinatal");
        AddIntervenciones("Hemorragia Pulmonar Originada En El Periodo Perinatal");
        AddIntervenciones("Displasia Broncopulmonar Originada  En El Periodo Perinatal");
        AddIntervenciones("Otras Apneas Del Recién Nacido");
        AddIntervenciones("Sepsis Bacteriana Del Recién Nacido");
        AddIntervenciones("Onfalitis  Del Recién Nacido Con O Sin Hemorragia Leve");
        AddIntervenciones("Hemorragia Intracraneal No Traumática Del Feto Y Del Recién Nacido");
        AddIntervenciones("Enfermedad Hemorrágica Del Feto Y Del Recién Nacido");
        AddIntervenciones("Enfermedad Hemolítica Del Feto Y Del Recién Nacido");
        AddIntervenciones("Hidropesía Fetal Debida A Enfermedad Hemolítica");
        AddIntervenciones("Ictericia Neonatal Debida A Otras Hemólisis  Excesivas");
        AddIntervenciones("Ictericia Neonatal Por Otras Causas Y Las No Especificadas");
        AddIntervenciones("Coagulación Intravascular Diseminada En El Feto Y El Recién Nacido");
        AddIntervenciones("Policitemia  Neonatal");
        AddIntervenciones("Trastornos Transitorios Del Metabolismo Delos Carbohidratos Específicos Del Feto Y Del Recién Nacido");
        AddIntervenciones("Trastornos Neonatales Transitorios Del Metabolismo Del Calcio Y Del Magnesio");
        AddIntervenciones("Alteraciones Del Equilibrio  Del Sodio En El Recién Nacido");
        AddIntervenciones("Alteraciones Del Equilibrio  Del Potasio En El Recién Nacido");
        AddIntervenciones("Síndrome  Del Tapón  De Meconio");
        AddIntervenciones("Otras Peritonitis Neonatales");
        AddIntervenciones("Enterocolitis Necrotizante");
        AddIntervenciones("Convulsiones Del Recién Nacido");
        AddIntervenciones("Depresión Cerebral  Neonatal");
        AddIntervenciones("Encefalopatía Hipóxica Isquémica");
        AddIntervenciones("Anencefalia");
        AddIntervenciones("Encefalocele");
        AddIntervenciones("Estenosis Y Estrechez Congénitas Del Conducto Lagrimal");
        AddIntervenciones("Catarata Congénita");
        AddIntervenciones("Otras Malformaciones Congénitas Del Oído (Microtia, Macrotia, Oreja Supernumeraria, Otras Deformidades Del Pabellón Auricular, Anomalía  De La Posición De La Oreja, Oreja Prominente)");
        AddIntervenciones("Seno, Fístula O Quiste De La Hendidura Branquial");
        AddIntervenciones("Malformaciones Congénitas De La Nariz");
        AddIntervenciones("Malformación Congénita De La Laringe (Incluye  Laringomalacia Congénita)");
        AddIntervenciones("Malformaciones Congénitas De La Tráquea  Y De Los Bronquios");
        AddIntervenciones("Malformaciones Congénitas Del Pulmón");
        AddIntervenciones("Otras Malformaciones Congénitas Del Intestino (Incluye Divertículo De Meckel, Enfermedad De Hirschsprung Y Malrotación Intestinal)");
        AddIntervenciones("Malformaciones Congénitas De Vesícula Biliar, Conductos  Biliares E Hígado (Incluye  Atresia De Conductos  Biliares Y Quiste De Colédoco)");
        AddIntervenciones("Páncreas  Anular");
        AddIntervenciones("Anquiloglosia");
        AddIntervenciones("Síndrome  De Potter");
        AddIntervenciones("Duplicación Del Uréter");
        AddIntervenciones("Riñón Supernumerario");
        AddIntervenciones("Riñón Ectópico");
        AddIntervenciones("Malformación Del Uraco");
        AddIntervenciones("Ausencia Congénita De La Vejiga Y De La Uretra");
        AddIntervenciones("Polidactilia");
        AddIntervenciones("Sindactilia");
        AddIntervenciones("Craneosinostosis");
        AddIntervenciones("Hernia Diafragmática Congénita");
        AddIntervenciones("Ictiosis Congénita");
        AddIntervenciones("Epidermólisis  Bullosa");
        AddIntervenciones("Nevo No Neoplásico,  Congénito");
        AddIntervenciones("Anormalidades Cromosómicas (Diagnóstico)");
        AddIntervenciones("Choque  Hipovolémico");
        AddIntervenciones("Fractura  De La Bóveda Del Cráneo");
        AddIntervenciones("Traumatismo Intracraneal Con Coma Prolongado");
        AddIntervenciones("Avulsión Del Cuero Cabelludo");
        AddIntervenciones("Herida  Del Tórax");
        AddIntervenciones("Traumatismo Por Aplastamiento Del Pulgar Y Otro(S) Dedo(S)");
        AddIntervenciones("Quemaduras De Tercer  Grado De Las Diferentes Partes Del Cuerpo");
        AddIntervenciones("Efectos Adversos De Drogas De Afectan  Primariamente El Sistema Nervioso Autónomo");
        AddIntervenciones("Efectos Adversos De Vacunas Bacterianas");
        AddIntervenciones("Atención  De Orificios Artificiales (Que Incluye Atención  De Traqueostomía, Gastrostomía, Ileostomía, Colostomía, Otros Orificios Artificiales  De Las Vías Digestivas, Cistostomía, Otros Orificios Artificiales  De Las Vías Urinarias Y Vagina Artificial)");

        return intervenciones;
    }

    private void AddIntervenciones(String intervencion){
        intervenciones.add(intervencion);
    }
}
